const assert=require('assert');
module.exports=async function dutySetupChecks(page,contrast){
  const impactHtml=await page.evaluate(()=>dutyImpactFields([{roster_id:'internal-roster-id',name:'年度班表 <核對>',status:'draft',date_from:'2026-01-01',date_to:'2026-12-31'}]));
  assert(impactHtml.includes('年度班表 &lt;核對&gt;｜草稿｜2026-01-01 至 2026-12-31'));
  assert(!impactHtml.includes('roster_id')&&!impactHtml.includes('internal-roster-id'));
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('[data-duty-tab="people"]').click();
  assert.equal(await page.locator('.duty-person-card').count(),16);
  await page.locator('[data-duty-action="person-new"]').click();
  const form=page.locator('[data-duty-form="person"]');
  await form.locator('[name="full_name"]').fill('範例員工01');
  await form.locator('[name="display_name"]').fill('範例暱稱01（補位驗證）');
  await form.locator('[name="department"]').fill('管理部');
  await form.locator('[name="floor"]').fill('2F');
  await form.locator('[name="position_id"]').selectOption({label:'代號 12（X）'});
  if(contrast)await contrast(page,'duty add person form');
  await form.locator('[type="submit"]').click();
  await page.waitForFunction(()=>document.querySelectorAll('.duty-person-card').length===17);
  const newCard=page.locator('.duty-person-card').filter({hasText:'範例暱稱01（補位驗證）'});
  await newCard.locator('[data-duty-action="binding"]').click();
  await page.getByText('尚未指定通知 OA，請先到「通知設定」指定，再綁定個人聯絡對象。').waitFor();
  assert(await page.getByRole('button',{name:'儲存 LINE 綁定',exact:true}).isDisabled());
  await page.locator('#modal-close').click();
  await newCard.locator('[data-duty-action="person-remove"]').click();
  await page.locator('[data-duty-form="remove"] [type="submit"]').click();
  await page.waitForFunction(()=>document.querySelectorAll('.duty-person-card').length===16);
  await page.locator('[data-duty-action="restore"]').click();
  await page.waitForFunction(()=>document.querySelectorAll('.duty-person-card').length===17);
  await page.locator('[data-duty-tab="tasks"]').click();
  const taskButton=page.locator('.duty-task-list button').filter({hasText:'掃地與擦拭（主機區域）'});
  await taskButton.click();
  await page.locator('[data-duty-action="task-preview"]').click();
  await page.locator('.duty-preview-day').first().waitFor();
  assert.equal(await page.locator('.duty-preview-day').count(),14);
  for(const width of [1440,768,390]){
    await page.setViewportSize({width,height:1000});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    if(contrast)await contrast(page,'duty populated task and preview '+width);
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('[data-duty-action="task-new"]').click();
  await page.locator('#modal [name="name"]').fill('垃圾打包（設定驗證）');
  await page.locator('#modal [data-duty-action="item-add"]').click();
  await page.locator('#modal [data-duty-item] [name="content"]').fill('打包垃圾');
  await page.locator('#modal [data-duty-item] [name="frequency"]').selectOption('weekly');
  await page.locator('#modal [data-duty-item] [name="weekdays"][value="0"]').check();
  await page.locator('#modal [data-duty-item] [name="weekdays"][value="3"]').check();
  await page.locator('#modal [data-duty-item] [name="reminder_time"]').fill('16:00');
  await page.locator('#modal [data-duty-form="task"] [type="submit"]').click();
  await page.locator('.duty-task-list button').filter({hasText:'垃圾打包（設定驗證）'}).waitFor();
  assert.equal(await page.locator('.duty-task-list button').count(),18);
  const detail=page.locator('#duty-task-detail [data-duty-form="task"]');
  await detail.locator('[name="name"]').fill('垃圾打包（設定新版）');
  await detail.locator('[type="submit"]').click();
  await page.locator('.duty-task-list button').filter({hasText:'垃圾打包（設定新版）'}).waitFor();
  assert((await page.locator('#duty-task-detail legend').first().textContent()).includes('v2'));
};
