const assert=require('assert');
module.exports=async function dutyRosterChecks(page,contrast){
  page.setDefaultTimeout(15000);
  await page.locator('[data-duty-tab="roster"]').click();
  await page.locator('[data-duty-roster-action="new"]').click();
  const create=page.locator('[data-duty-form="roster-create"]');
  await create.locator('[name="name"]').fill('十月排班驗證');
  await create.locator('[name="date_from"]').fill('2026-10-01');
  await create.locator('[name="date_to"]').fill('2026-10-31');
  await create.locator('[data-duty-roster-action="wizard-next"]').click();
  await create.locator('[data-duty-roster-action="wizard-next"]').click();
  await create.locator('[type="submit"]').click();
  await page.locator('[data-duty-form="roster-editor"]').waitFor();
  await page.locator('[data-duty-roster-action="view"][data-id="work"]').click();
  assert((await page.locator('[data-duty-roster-action="choose"]').first().textContent()).startsWith('編輯負責人：'));
  await page.locator('[data-duty-roster-action="choose"]').first().click();
  const choose=page.locator('[data-duty-form="roster-choose"]');
  const firstName=await choose.locator('[name="person_ids"]').first().getAttribute('data-name');
  for(const [width,height] of [[1440,1000],[2560,1080],[3440,1440],[2560,720],[1280,600],[768,1000],[390,844]]){
    await page.setViewportSize({width,height});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    const geometry=await choose.evaluate(form=>{
      const dialog=form.closest('dialog'),body=dialog.querySelector('#modal-body'),footer=form.querySelector('.duty-picker-footer'),rect=dialog.getBoundingClientRect(),bottom=footer.getBoundingClientRect();
      return {width:rect.width,columns:getComputedStyle(form.querySelector('.duty-person-choice-grid')).gridTemplateColumns.split(' ').length,top:rect.top,bottom:rect.bottom,footerVisible:bottom.top>=rect.top&&bottom.bottom<=rect.bottom,scrollable:body.scrollHeight>body.clientHeight,workloadSingleLine:[...form.querySelectorAll('.duty-choice-workload')].every(el=>el.getBoundingClientRect().height<parseFloat(getComputedStyle(el).lineHeight)*1.5&&el.scrollWidth<=el.clientWidth)};
    });
    assert.equal(geometry.columns,width>768?2:1);
    if(width>=1280)assert(geometry.width>=900,'shared dialog density must not narrow the PC picker');
    assert(geometry.top>=0&&geometry.bottom<=height,'picker must fit viewport height');
    assert(geometry.workloadSingleLine,'workload must fit without wrapping or clipping');
    if(width>768)assert(geometry.footerVisible,'apply button must remain visible on short PC screens');
    if(contrast)await contrast(page,'duty person picker '+width);
    if(!contrast)await page.locator('#modal').screenshot({path:`test-results/workspace_browser/duty-person-picker-${width}x${height}.png`});
  }
  await page.setViewportSize({width:1440,height:1000});
  await choose.locator('[data-roster-person-search]').fill(firstName);
  assert.equal(await choose.locator('[data-person-choice]:visible').count(),1);
  await choose.locator('[data-roster-person-search]').fill('不存在的人員');
  assert(await choose.locator('[data-person-empty]').isVisible());
  await choose.locator('[data-roster-person-search]').fill('');
  await choose.locator('[name="person_ids"]').first().check();
  assert.equal(await choose.locator('[name="unassigned"]').isChecked(),false);
  assert((await choose.locator('[data-person-selection]').textContent()).includes(firstName));
  await choose.locator('[name="unassigned"]').check();
  assert.equal(await choose.locator('[name="person_ids"]:checked').count(),0);
  await choose.locator('[name="person_ids"]').first().check();
  await choose.locator('[type="submit"]').click();
  await page.locator('[data-duty-roster-action="substitute"]').first().click();
  const sub=page.locator('[data-duty-form="roster-substitute"]');
  await sub.locator('[name="substitute_person_id"]').selectOption({index:1});
  await sub.locator('[name="date_from"]').fill('2026-10-08');
  await sub.locator('[name="date_to"]').fill('2026-10-09');
  await sub.locator('[type="submit"]').click();
  await page.locator('[data-duty-form="roster-editor"] [type="submit"]').click();
  await page.waitForFunction(()=>document.querySelector('[data-duty-form="roster-editor"]')?.dataset.dirty!=='true'&&document.querySelector('.duty-save-state')?.textContent.startsWith('已儲存'));
  for(const width of [1440,768,390]){
    await page.setViewportSize({width,height:1000});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),JSON.stringify(await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth&&getComputedStyle(e).display!=='none').slice(0,8).map(e=>e.tagName+'.'+e.className)}))));
    if(contrast)await contrast(page,'duty roster draft '+width);
  }
  await page.setViewportSize({width:1440,height:1000});
  assert.equal(await page.locator('[data-roster-period]').count(),0);
  const monthId=await page.evaluate(()=>dutyRoster.record.roster_id);
  await page.evaluate(async()=>{await api('/api/duty/roster/create',{name:'年度編輯驗證',period_type:'year',date_from:'2026-01-01',date_to:'2026-12-31'});await loadDutyRosters();});
  await page.locator('.duty-period-navigation [data-id="year"]').click();
  await page.waitForFunction(()=>dutyRoster.record.period_type==='year');
  assert.equal(await page.locator('.duty-assignment-list .duty-assignment-card').count(),2);
  assert.equal(await page.locator('[data-duty-roster-action="choose"]').count(),2);
  assert.equal(await page.locator('.duty-related-work').getAttribute('open'),null);
  await page.locator('[data-duty-roster-action="choose"]').first().click();
  await page.locator('[data-duty-form="roster-choose"] [name="person_ids"]').first().check();
  await page.locator('[data-duty-form="roster-choose"] [type="submit"]').click();
  page.once('dialog',dialog=>dialog.dismiss());
  await page.locator('.duty-period-navigation [data-id="month"]').click();
  assert.equal(await page.evaluate(()=>dutyRoster.record.period_type),'year');
  await page.locator('[data-duty-form="roster-editor"] [type="submit"]').click();
  await page.waitForFunction(()=>!dutyRoster.saving&&document.querySelector('[data-duty-form="roster-editor"]')?.dataset.dirty!=='true'&&document.querySelector('.duty-save-state')?.textContent.startsWith('已儲存'));
  for(const width of [1440,768,390]){
    await page.setViewportSize({width,height:1000});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    if(width<=850)await page.waitForFunction(()=>document.querySelector('#sidebar').getBoundingClientRect().right<=1);
    if(contrast)await contrast(page,'duty annual focused editor '+width);
    if(!contrast)await page.screenshot({path:`test-results/workspace_browser/duty-annual-${width}.png`,fullPage:true});
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('.duty-period-navigation [data-id="month"]').click();
  await page.waitForFunction(id=>dutyRoster.record.roster_id===id,monthId);
  assert.equal(await page.locator('.duty-assignment-list .duty-assignment-card').count(),15);
  async function publish(reason){
    assert.notEqual(await page.locator('[data-duty-form="roster-editor"]').getAttribute('data-dirty'),'true');
    await page.locator('[data-duty-roster-action="publish"]').click();
    const form=page.locator('[data-duty-form="roster-publish"]');
    await form.waitFor();
    for(const checkbox of await form.locator('[name="acknowledged"]').all())await checkbox.check();
    await form.locator('[data-duty-roster-action="wizard-next"]').click();
    assert((await form.textContent()).includes('本次 push 則數：0'));
    if(contrast)await contrast(page,'duty publish preview');
    await form.locator('[data-duty-roster-action="wizard-next"]').click();
    if(reason)await form.locator('[name="reason"]').fill(reason);
    const published=page.waitForResponse(r=>r.url().includes('/api/duty/roster/publish'));
    await form.locator('[type="submit"]').click();
    const response=await published;
    assert.equal(response.status(),200,await response.text());
    await form.waitFor({state:'hidden'});
    await page.waitForFunction(()=>document.querySelector('.callout')?.textContent.includes('已發布 v'));
  }
  await publish();
  assert((await page.locator('.callout').first().textContent()).includes('已發布 v1'));
  assert.equal(await page.locator('[data-duty-roster-action="choose"]').count(),0);
  await page.locator('[data-duty-roster-action="back"]').click();
  await page.locator(`[data-duty-roster-action="copy"][data-id="${monthId}"]`).click();
  const copy=page.locator('[data-duty-form="roster-create"]');
  await copy.locator('[data-duty-roster-action="wizard-next"]').click();
  await copy.locator('[data-duty-roster-action="wizard-next"]').click();
  const createdResponse=page.waitForResponse(response=>response.url().includes('/api/duty/roster/create'));
  await copy.locator('[type="submit"]').click();
  const response=await createdResponse;
  assert.equal(response.status(),200,await response.text());
  await page.waitForFunction(id=>dutyRoster.record?.status==='draft'&&dutyRoster.record.roster_id!==id,monthId).catch(async error=>{throw new Error(error.message+' '+JSON.stringify(await page.evaluate(()=>({record:dutyRoster.record?.name,status:dutyRoster.record?.status,formError:document.querySelector('.duty-form-error:not([hidden])')?.textContent,toast:document.querySelector('#floating-toast')?.textContent}))));});
  await publish('驗證重新發布版本保留');
  assert((await page.locator('.callout').first().textContent()).includes('已發布 v2'));
  await page.locator('[data-duty-roster-action="versions"]').click();
  await page.locator('[data-duty-roster-action="version-open"]').filter({hasText:'v1'}).click();
  await page.waitForFunction(()=>document.querySelector('.callout')?.textContent.includes('已取代 v1'));
  assert((await page.locator('.callout').first().textContent()).includes('已取代 v1'));
  assert.equal(await page.locator('[data-duty-roster-action="choose"]').count(),0);
};
