const assert=require('assert');
const fs=require('fs');
module.exports=async function formsBrowserChecks(browser,access,contrast){
  const base=`http://127.0.0.1:${access.port}`,url=`${base}/?view=forms#${access.token}`;
  const context=await browser.newContext({viewport:{width:1440,height:1000},extraHTTPHeaders:{'X-Fixture-Role':'org_admin'}}),page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  const contrastResults=[];
  const check=async label=>{
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Forms overflow: '+label);
    if(contrast)contrastResults.push(await contrast(page,'forms '+label));
  };
  try{
    await page.goto(url);await page.getByRole('heading',{name:'表單',exact:true}).waitFor();
    assert(await page.locator('nav [data-view="forms"]').isVisible());
    await check('empty list');
    await page.locator('[data-action="form-new"]').click();await page.locator('[data-form-create-mode=template]').click();
    await page.locator('[name="template_id"]').selectOption('group_buy');
    await page.locator('#modal [name="name"]').fill('驗收團購');
    await check('create dialog');
    await page.getByRole('button',{name:'建立草稿',exact:true}).click();
    await page.locator('#page [data-form-editor]').waitFor();
    assert.equal(await page.locator('.form-question-summary li').count(),4);
    const id=await page.locator('#page [data-form-editor]').getAttribute('data-id');
    await page.locator('#page [name="description"]').fill('中文說明\n保留換行');
    await page.locator('#page [name="deadline_at"]').fill('2099-01-01T08:00');
    let dialogSeen=false;
    page.once('dialog',async dialog=>{dialogSeen=true;await dialog.dismiss();});
    await page.locator('[data-action="form-back"]').click();
    assert(dialogSeen);assert(await page.locator('#page [data-form-editor]').isVisible());
    await page.locator('[data-workspace-tool="related"]').click();
    await page.locator('[data-workspace-tool-action]').filter({hasText:'儲存基本資料'}).click();
    await page.waitForFunction(()=>document.querySelector('#page [data-form-editor]')?.dataset.dirty==='false');
    assert.equal(await page.locator('#page [name="description"]').inputValue(),'中文說明\n保留換行');
    if(await page.locator('[data-workspace-tool-close]').isVisible())await page.locator('[data-workspace-tool-close]').click();
    await check('saved editor');
    await page.locator('[data-action="form-status"]').click();
    await page.waitForFunction(()=>document.querySelector('.form-status')?.textContent.includes('收件中'));
    await page.locator('[data-action="form-status"]').click();
    await page.waitForFunction(()=>document.querySelector('.form-status')?.textContent.includes('停止收件'));
    await page.locator('#page [name="deadline_at"]').fill('2000-01-01T08:00');
    await page.getByRole('button',{name:'儲存基本資料',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#page [data-form-editor]')?.dataset.dirty==='false');
    await page.locator('[data-action="form-status"]').click();
    await page.waitForFunction(()=>document.getElementById('floating-toast')?.textContent.includes('截止時間已過'));
    assert((await page.locator('.form-status').textContent()).includes('停止收件'));
    await page.locator('#page [name="deadline_at"]').fill('2099-01-01T08:00');
    await page.getByRole('button',{name:'儲存基本資料',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#page [data-form-editor]')?.dataset.dirty==='false');
    await page.locator('[data-action="form-status"]').click();
    await page.waitForFunction(()=>document.querySelector('.form-status')?.textContent.includes('收件中'));
    for(const [width,height] of [[1440,1000],[768,960],[390,844]]){
      await page.setViewportSize({width,height});await check('editor '+width);
      await page.locator('[data-workspace-tool="outline"]').click();
      assert((await page.locator('#workspace-tools-body').textContent()).includes('基本資料'));
      await check('outline '+width);await page.locator('[data-workspace-tool-close]').click();
      if(!contrast)await page.screenshot({path:`test-results/workspace_browser/forms-editor-${width}.png`,fullPage:true});
    }
    await page.locator('[data-action="form-back"]').click();
    await page.locator(`[data-action="form-copy"][data-id="${id}"]`).click();
    await page.getByRole('heading',{name:'驗收團購（副本）',exact:true}).waitFor();
    assert((await page.locator('.form-status').textContent()).includes('草稿'));
    const copyId=await page.locator('#page [data-form-editor]').getAttribute('data-id');
    assert.notEqual(copyId,id);
    await page.locator('[data-action="form-back"]').click();
    await page.locator('#form-search').fill('副本');assert.equal(await page.locator('.form-card').count(),1);
    await page.locator('[data-action="form-delete"]').click();
    await page.locator('[data-action="form-confirm-delete"]').waitFor();
    assert((await page.locator('#modal-body').textContent()).includes('0 份通知、0 份回覆'));
    await check('delete dialog mobile');
    await page.locator('[data-action="form-confirm-delete"]').click();
    await page.waitForFunction(()=>!document.querySelector('dialog[open]'));
    assert.equal((await page.evaluate(id=>api('/api/forms/detail?form_id='+id).catch(e=>({status:e.status})),copyId)).status,403);
    await page.locator('#form-search').fill('');await page.locator('#form-filter').selectOption('collecting');
    assert.equal(await page.locator('.form-card').count(),1);await check('filtered list mobile');
    const operator=await browser.newContext({viewport:{width:768,height:960},extraHTTPHeaders:{'X-Fixture-Role':'operator'}});
    const opPage=await operator.newPage();opPage.on('pageerror',e=>errors.push(e.message));
    await opPage.goto(url);await opPage.locator(`.btn[data-action="form-open"][data-id="${id}"]`).click();
    await opPage.getByRole('button',{name:'儲存基本資料',exact:true}).waitFor();
    assert(await opPage.getByRole('button',{name:'儲存基本資料',exact:true}).isVisible());
    await operator.close();
    const readonly=await browser.newContext({viewport:{width:390,height:844},extraHTTPHeaders:{'X-Fixture-Role':'collaborator'}});
    const roPage=await readonly.newPage();roPage.on('pageerror',e=>errors.push(e.message));
    await roPage.goto(url);await roPage.locator(`.btn[data-action="form-open"][data-id="${id}"]`).click();
    await roPage.locator('#page [data-form-editor]').waitFor();
    assert.equal(await roPage.locator('[data-action="form-status"]').count(),0);
    assert.equal(await roPage.locator('[data-form-editor] [type="submit"]').count(),0);
    assert(await roPage.locator('#page [name="name"]').isDisabled());
    assert.equal((await roPage.evaluate(id=>api('/api/forms/save',{form_id:id,name:'越權'}).catch(e=>({status:e.status})),id)).status,403);
    if(contrast)contrastResults.push(await contrast(roPage,'forms collaborator readonly mobile'));
    await readonly.close();
    const disabled=await browser.newContext({extraHTTPHeaders:{'X-Fixture-Role':'org_admin'}}),disabledPage=await disabled.newPage();
    await disabledPage.addInitScript(()=>localStorage.setItem('lineWorkspaceOrganization:company-admin@example.test','第二公司'));
    await disabledPage.goto(url);await disabledPage.waitForFunction(()=>document.querySelector('#connection').textContent.includes('已連線'));
    assert(await disabledPage.locator('nav [data-view="forms"]').isHidden());
    assert.equal((await disabledPage.evaluate(()=>api('/api/forms').catch(e=>({status:e.status})))).status,403);
    await disabled.close();
    // Cleanup our original form so existing workspace suites see their original fixture.
    await page.evaluate(id=>api('/api/forms/delete',{form_id:id,confirm_counts:{notifications:0,responses:0}}),id);
    assert.deepEqual(errors,[]);
    if(contrast)fs.writeFileSync('test-results/workspace_contrast/forms-contrast.json',JSON.stringify(contrastResults,null,2));
  }catch(error){
    console.error('Forms browser failure:',await page.locator('#floating-toast').allTextContents(),await page.locator('.form-status').allTextContents());
    throw error;
  }finally{await context.close();}
};
