// Run from the repository root. Requires Playwright via PLAYWRIGHT_MODULE or an installed package.
const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'@playwright/test');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
(async()=>{
  const dir=path.resolve('test-results/workspace_browser');fs.mkdirSync(dir,{recursive:true});
  const stateFile=path.join(dir,`ui-fixture-${Date.now()}.json`),stopFile=stateFile.replace(/\.json$/,'.stop');
  const child=spawn(path.resolve('.venv/Scripts/python.exe'),['tests/workspace_fixture.py',stateFile],{windowsHide:true,stdio:['ignore','ignore','pipe']});
  let stderr='';child.stderr.on('data',data=>{stderr+=data;});let browser;
  try{
    for(let i=0;i<100&&!fs.existsSync(stateFile);i++){if(child.exitCode!==null)throw Error(stderr);await delay(100);}
    const access=JSON.parse(fs.readFileSync(stateFile,'utf8')),url=`http://127.0.0.1:${access.port}/#${access.token}`;
    browser=await chromium.launch({channel:'chrome',headless:true});
    const context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage(),errors=[];
    page.on('pageerror',error=>errors.push(error.message));
    await page.goto(url);await page.getByRole('heading',{name:'今天的工作，一目了然'}).waitFor();
    // Light-only: an OS dark preference must not change the page or offer a theme picker.
    await page.emulateMedia({colorScheme:'dark'});
    assert.equal(await page.getByRole('group',{name:'介面色系'}).count(),0);
    assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).colorScheme),'light');
    assert((await page.locator('.brand-logo').getAttribute('src')).endsWith('-light.png'));
    assert.notEqual((await page.request.get(new URL('/appearance.js',page.url()).href)).status(),200);
    await page.emulateMedia({colorScheme:'light'});
    await page.locator('.feature img').waitFor();
    await page.screenshot({path:path.join(dir,'workspace-desktop.png'),fullPage:true});
    await page.locator('nav [data-view="reports"]').click();
    await page.reload();await page.getByRole('heading',{name:'報告中心',exact:true}).waitFor();
    assert.equal(await page.locator('.report-card').count(),4);
    // Search and inspectors use the loaded, authorized records and preserve real actions.
    await page.locator('#report-search').fill('每日營運');
    assert.equal(await page.locator('.report-card').count(),1);
    await page.locator('[data-action="report-detail"]').click();
    assert.equal(await page.locator('#report-detail-title').textContent(),'每日營運數據');
    await page.locator('[data-action="close-report-detail"]').click();
    assert.equal(await page.evaluate(()=>document.activeElement.dataset.action),'report-detail');
    await page.locator('#report-search').fill('沒有這份報告');
    await page.getByRole('heading',{name:'沒有符合的報告'}).waitFor();
    await page.locator('#report-search').fill('');
    await page.locator('[data-action="report-layout"][data-id="grid"]').click();
    assert.equal(await page.locator('.report-grid.list-layout').count(),0);
    await page.locator('[data-action="report-layout"][data-id="list"]').click();
    await page.keyboard.press('Control+k');
    await page.locator('#command-search').fill('每日營運');
    await page.keyboard.press('Enter');
    await page.locator('#report-detail').waitFor();
    assert.equal(await page.locator('#command-dialog').evaluate(el=>el.open),false);
    await page.locator('[data-action="close-report-detail"]').click();
    await page.keyboard.press('Control+k');
    await page.locator('#command-search').fill('同事 2');
    await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
    await page.locator('#contact-detail').waitFor();
    await page.locator('[data-action="close-contact-detail"]').click();
    assert.equal(await page.evaluate(()=>document.activeElement.dataset.action),'contact-detail');
    await page.locator('nav [data-view="reports"]').click();
    // Built-in reports can be removed through confirmation and restored after reload.
    await page.locator('[data-action="remove-report"][data-id="weather"]').click();
    await page.getByRole('heading',{name:'移除報告來源',exact:true}).waitFor();
    await page.locator('#modal-close').click();
    assert.equal(await page.locator('.report-card').count(),4);
    await page.locator('[data-action="remove-report"][data-id="weather"]').click();
    await page.locator('[data-action="confirm-remove-report"]').click();
    await page.waitForFunction(()=>document.querySelectorAll('.report-card').length===3);
    await page.reload();await page.locator('[data-action="restore-weather"]').waitFor();
    assert.equal(await page.locator('[data-action="choose-report"][data-id="weather"]').count(),0);
    await page.locator('[data-action="restore-weather"]').click();
    await page.waitForFunction(()=>document.querySelectorAll('.report-card').length===4);
    await page.locator('[data-action="choose-report"][data-id="weather"]').click();
    await page.locator('#contact-search').fill('同事');
    await page.locator('[data-select]').first().check();
    await page.locator('#review-button').click();
    await page.getByRole('heading',{name:'確認這次的發送內容'}).waitFor();
    let payload;await page.route('**/api/send',route=>{payload=route.request().postDataJSON();return route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({job_id:payload.job_id})});});
    await page.locator('#submit-send').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('發送工作已建立'));
    assert.equal(payload.report_id,'weather');assert.equal(payload.ids.length,1);assert.equal(payload.report_version.length,64);assert(!payload.image_path);
    await page.locator('nav [data-view="contacts"]').click();
    await page.locator('[data-action="edit-contact"]').first().click();
    await page.locator('#contact-form [name="custom_name"]').fill('測試備註');
    await page.getByRole('button',{name:'儲存聯絡對象',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent==='設定已儲存。');
    await page.locator('nav [data-view="organizations"]').click();
    await page.locator('[data-action="mg-org"][data-id="示範公司"]').click();
    await page.locator('[data-action="mg-tab"][data-id="admins"]').click();
    await page.locator('[data-action="new-org-admin"]').first().click();
    await page.locator('#account-form [name="email"]').fill('newstaff@example.test');
    await page.locator('#account-form [name="display_name"]').fill('新增員工');
    await page.locator('#account-form [name="organization_id"]').selectOption('示範公司');
    await page.getByRole('button',{name:'儲存帳號',exact:true}).click();
    await page.locator('[data-action="edit-account"][data-id="newstaff@example.test"]').waitFor();
    await page.locator('nav [data-view="reports"]').click();
    await page.locator('[data-action="edit-report"]').first().click();
    await page.locator('#report-form [name="title"]').fill('營運日報更新');
    await page.getByRole('button',{name:'儲存報告來源',exact:true}).click();
    await page.getByRole('heading',{name:'營運日報更新',exact:true}).waitFor();
    await page.locator('#switch-view').click();
    await page.locator('[data-action="apply-view"][data-id="sender@example.test|示範公司"]').click();
    await page.locator('#view-banner').waitFor();
    await page.getByRole('heading',{name:'報告中心',exact:true}).waitFor();
    assert.equal(await page.locator('.report-card').count(),2);
    assert.equal(await page.locator('[data-action="choose-report"]').count(),0);
    assert.equal(await page.locator('nav [data-view="organizations"]').isVisible(),false);
    await page.reload();await page.locator('#view-banner').waitFor();
    assert((await page.locator('#view-description').textContent()).includes('sender@example.test'));
    await page.locator('#view-banner button').click();
    await page.getByRole('heading',{name:'今天的工作，一目了然'}).waitFor();
    assert.equal(await page.locator('#view-banner').isVisible(),false);
    assert.equal(await page.locator('nav [data-view="organizations"]').isVisible(),true);
    assert.equal(await page.locator('nav [data-view="personnel"]').isVisible(),false);
    await page.unroute('**/api/send');
    await page.locator('nav [data-view="send"]').click();
    await page.locator('#message-draft').fill('隔離測試：明日會議提醒');
    await page.locator('[data-action="choose-text"]').click();
    await page.locator('[data-select]').first().check();await page.locator('#review-button').click();
    await page.locator('#send-timing').selectOption('scheduled');
    const future=new Date(Date.now()+86400000+8*3600000).toISOString().slice(0,16);
    await page.locator('#scheduled-time').fill(future);
    await page.locator('#submit-send').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已建立預約'));
    await page.locator('nav [data-view="schedule"]').click();
    await page.getByRole('heading',{name:'排程管理',exact:true}).waitFor();
    assert.equal(await page.locator('[data-action="cancel-schedule"]').count(),1);
    await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Scheduled date overflows mobile page');
    await page.locator('.schedule-list .history-item summary').first().click();
    await page.locator('[data-action="cancel-schedule"]').click();
    await page.locator('[data-action="confirm-cancel-schedule"]').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent==='預約已取消。');
    await page.setViewportSize({width:390,height:844});
    await page.locator('#menu').click();await page.locator('nav [data-view="reports"]').click();
    await page.locator('.report-card').first().waitFor();await page.screenshot({path:path.join(dir,'workspace-mobile.png'),fullPage:true});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile page overflows horizontally');
    await page.locator('[data-action="choose-report"][data-id="weather"]').click();await page.locator('[data-select]').first().check();
    await page.locator('#review-button').click();await page.screenshot({path:path.join(dir,'workspace-mobile-confirm.png'),fullPage:true});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile confirmation overflows');
    const contactContext=await browser.newContext({viewport:{width:1280,height:900},extraHTTPHeaders:{'X-Fixture-Role':'contact'}});
    assert.equal((await contactContext.request.get(`http://127.0.0.1:${access.port}/api/session`,{headers:{Authorization:`Bearer ${access.token}`}})).status(),403);
    const companyContext=await browser.newContext({viewport:{width:1440,height:1000},extraHTTPHeaders:{'X-Fixture-Role':'org_admin'}}),companyPage=await companyContext.newPage();
    companyPage.on('pageerror',error=>errors.push(error.message));
    await companyPage.goto(url);await companyPage.getByRole('heading',{name:'今天的工作，一目了然'}).waitFor();
    await companyPage.locator('#command-open').click();
    await companyPage.locator('#command-search').fill('其他公司報告');
    assert.equal(await companyPage.locator('.command-result').count(),0);
    await companyPage.locator('#command-search').fill('組織管理');
    assert.equal(await companyPage.locator('.command-result').count(),0);
    await companyPage.keyboard.press('Escape');
    assert.equal(await companyPage.locator('nav [data-view="subscriptions"]').isVisible(),false);
    await companyPage.locator('nav [data-view="reports"]').click();
    assert.equal(await companyPage.locator('.report-card').count(),2);
    assert.equal(await companyPage.locator('[data-action="new-report"]').count(),0);
    assert.equal(await companyPage.locator('[data-action="edit-report"]').count(),0);
    await companyPage.locator('nav [data-view="contacts"]').click();
    await companyPage.locator('[data-action="edit-contact"]').first().click();
    assert.equal(await companyPage.locator('#contact-form [name="organization_label"]').getAttribute('readonly'),'');
    assert.equal(await companyPage.locator('#contact-form [name="subscribed"]').count(),0);
    await companyPage.locator('#contact-form [name="custom_name"]').fill('公司範圍備註');
    await companyPage.getByRole('button',{name:'儲存聯絡對象',exact:true}).click();
    await companyPage.waitForFunction(()=>document.querySelector('#notice').textContent==='設定已儲存。');
    assert.equal(await companyPage.locator('nav [data-view="organizations"]').isVisible(),false);
    assert.equal(await companyPage.locator('nav [data-view="personnel"]').isVisible(),true);
    assert.equal(await companyPage.locator('nav [data-view="org-settings"]').isVisible(),true);
    await companyPage.screenshot({path:path.join(dir,'workspace-company-admin.png'),fullPage:true});
    await companyPage.locator('#organization-select').selectOption('第二公司');
    await companyPage.getByRole('heading',{name:'今天的工作，一目了然'}).waitFor();
    assert.equal(await companyPage.locator('nav [data-view="organizations"]').isVisible(),false);
    await companyPage.locator('nav [data-view="reports"]').click();
    assert.equal(await companyPage.locator('.report-card').count(),1);
    await companyPage.reload();await companyPage.locator('.report-card').first().waitFor();
    assert.equal(await companyPage.locator('#organization-select').inputValue(),'第二公司');
    await companyPage.locator('#organization-select').selectOption('示範公司');
    await companyPage.getByRole('heading',{name:'今天的工作，一目了然'}).waitFor();
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('nav [data-view="organizations"]').click();
    await page.locator('[data-action="mg-org"][data-id="示範公司"]').click();
    await page.locator('[data-action="mg-tab"][data-id="scopes"]').click();
    await page.locator('[data-action="new-dispatch-scope"]').click();
    await page.locator('#dispatch-scope-form [name="organization_id"]').selectOption('示範公司');
    await page.locator('#dispatch-scope-form [name="name"]').fill('營運部發送範圍');
    await page.locator('#dispatch-scope-form [name="department"]').fill('營運部');
    await page.getByRole('button',{name:'儲存範圍',exact:true}).click();
    await page.getByText('營運部發送範圍',{exact:true}).waitFor();
    await page.locator('[data-action="mg-tab"][data-id="people"]').click();
    await page.locator('[data-action="edit-sender-grant"][data-id="sender@example.test|示範公司"]').click();
    await page.locator('#sender-grant-form [name="messaging"]').check();
    await page.locator('#sender-grant-form [name="reports"]').check();
    await page.locator('#sender-grant-form [name="scope_ids"]').check();
    await page.locator('#sender-grant-form [name="report_ids"]:not([value="weather"])').first().check();
    await page.screenshot({path:path.join(dir,'sender-permissions.png'),fullPage:true});
    await page.getByRole('button',{name:'儲存授權',exact:true}).click();
    await page.waitForFunction(()=>!document.querySelector('#modal').open);
    const senderContext=await browser.newContext({viewport:{width:1280,height:900},extraHTTPHeaders:{'X-Fixture-Role':'operator'}}),senderPage=await senderContext.newPage();
    senderPage.on('pageerror',error=>errors.push(error.message));
    await senderPage.goto(url);await senderPage.getByRole('heading',{name:'今天的工作，一目了然'}).waitFor();
    assert.equal(await senderPage.locator('#management-nav-label').isVisible(),false);
    for(const view of ['organizations','channels','personnel','org-settings'])assert.equal(await senderPage.locator(`nav [data-view="${view}"]`).isVisible(),false);
    await senderPage.locator('nav [data-view="reports"]').click();
    assert.equal(await senderPage.locator('.report-card').count(),1);
    await senderPage.locator('nav [data-view="contacts"]').click();
    assert.equal(await senderPage.locator('[data-action="edit-contact"]').count(),0);
    assert.equal(await senderPage.locator('[data-action="profiles"]').count(),0);
    await senderPage.locator('nav [data-view="send"]').click();
    await senderPage.locator('#message-draft').fill('隔離測試：主管預約通知');
    await senderPage.locator('[data-action="choose-text"]').click();
    await senderPage.locator('[data-select]').first().check();await senderPage.locator('#review-button').click();
    await senderPage.locator('#send-timing').selectOption('scheduled');
    await senderPage.locator('#scheduled-time').fill(new Date(Date.now()+3600000+8*3600000).toISOString().slice(0,16));
    await senderPage.locator('#submit-send').click();
    await senderPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('預約'));
    await senderPage.locator('nav [data-view="history"]').click();
    await senderPage.locator('.history-item summary').first().click();
    await senderPage.locator('[data-action="cancel-schedule"]').click();
    await senderPage.locator('[data-action="confirm-cancel-schedule"]').click();
    await senderPage.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已取消'));
    await senderContext.close();
    await page.locator('[data-action="new-organization"]').click();
    await page.locator('#organization-form [name="name"]').fill('晨跑俱樂部');
    await page.locator('#organization-form [name="kind"]').selectOption('club');
    await page.getByRole('button',{name:'儲存組織',exact:true}).click();
    await page.locator('[data-action="mg-org"][aria-pressed="true"]').filter({hasText:'晨跑俱樂部'}).waitFor();
    await page.locator('[data-action="new-membership"]').click();
    await page.locator('#membership-form [name="email"]').selectOption('newstaff@example.test');
    await page.locator('#membership-form [name="org_id"]').selectOption({label:'晨跑俱樂部'});
    await page.locator('#membership-form [name="role"]').selectOption('org_admin');
    await page.getByRole('button',{name:'儲存成員資格',exact:true}).click();
    await page.locator('.mg-row').filter({hasText:'newstaff@example.test'}).filter({hasText:'管理員'}).waitFor();
    await page.screenshot({path:path.join(dir,'workspace-organizations.png'),fullPage:true});
    // Organization selection scopes people/ranges and prefills new forms.
    await page.locator('#mg-org-search').fill('不存在的組織');
    assert.equal(await page.locator('[data-action="mg-org"]').count(),0);
    await page.locator('#mg-org-search').fill('');
    await page.locator('#mg-people-search').fill('newstaff');
    assert.equal(await page.locator('.mg-row').count(),1);
    await page.locator('#mg-people-search').fill('找不到的人');
    await page.getByText('沒有符合的人員',{exact:true}).waitFor();
    await page.locator('#mg-people-search').fill('');
    await page.locator('[data-action="new-account"]').click();
    assert.equal(await page.locator('#account-form [name="organization_id"]').inputValue(),await page.locator('[data-action="mg-org"][aria-pressed="true"]').getAttribute('data-id'));
    await page.locator('#account-form [name="role"]').selectOption('platform_admin');
    assert((await page.locator('.mg-role-help').textContent()).includes('管理所有組織'));
    await page.locator('#modal-close').click();
    await page.locator('[data-action="mg-tab"][data-id="scopes"]').click();
    assert.equal(await page.getByText('營運部發送範圍',{exact:true}).count(),0);
    await page.locator('[data-action="mg-tab"][data-id="modules"]').click();
    await page.getByText('這個組織可以使用什麼？',{exact:true}).waitFor();
    await page.locator('[data-action="mg-tab"][data-id="people"]').click();
    await page.setViewportSize({width:390,height:844});
    await page.waitForFunction(()=>document.querySelector('#sidebar').inert&&!document.body.classList.contains('nav-open'));
    await page.locator('#mg-mobile-org').selectOption('示範公司');
    await page.locator('[data-action="edit-sender-grant"][data-id="sender@example.test|示範公司"]').waitFor();
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Management mobile layout overflows');
    await page.screenshot({path:path.join(dir,'management-mobile.png'),fullPage:true,animations:'disabled'});
    await page.setViewportSize({width:1440,height:1000});
    await page.locator('nav [data-view="organizations"]').click();
    await page.locator('[data-action="mg-org"][data-id="示範公司"]').click();
    await page.locator('[data-action="mg-tab"][data-id="admins"]').click();
    await page.locator('[data-action="edit-account"][data-id="newstaff@example.test"]').waitFor();
    await page.screenshot({path:path.join(dir,'management-accounts.png'),fullPage:true,animations:'disabled'});

    // Device picker: save a new report without entering a server path.
    await page.locator('nav [data-view="reports"]').click();
    await page.locator('[data-action="new-report"]').click();
    await page.locator('#report-form [name="title"]').fill('從裝置上傳的報告');
    await page.locator('#report-form [name="organization_id"]').selectOption('示範公司');
    await page.locator('#report-file').setInputFiles(access.sample_image);
    await page.locator('#report-upload-preview img').waitFor();
    assert.equal(await page.locator('#report-form [name="source_path"]').inputValue(),'');
    assert.equal((await page.locator('#report-form [name="asset_id"]').inputValue()).length,32);
    await page.getByRole('button',{name:'儲存報告來源',exact:true}).click();
    await page.getByRole('heading',{name:'從裝置上傳的報告',exact:true}).waitFor();
    await page.locator('nav [data-view="send"]').click();
    // Return from the previous confirmation and build a two-card carousel.
    if(await page.locator('[data-action="back-recipients"]').count())await page.locator('[data-action="back-recipients"]').click();
    if(await page.locator('[data-action="back-report"]').count())await page.locator('[data-action="back-report"]').click();
    await page.locator('[data-action="message-format"][data-id="carousel"]').click();
    await page.locator('#asset-company').selectOption('示範公司');
    await page.locator('#composition-files').setInputFiles([access.sample_image,access.sample_image]);
    await page.waitForFunction(()=>document.querySelector('#upload-status').textContent.includes('已選擇 2 張'));
    for(let i=0;i<2;i++){
      await page.locator(`[data-card="${i}"][data-prop="title"]`).fill('卡片 '+(i+1));
      await page.locator(`[data-card="${i}"][data-prop="text"]`).fill('本週營運數據與重點摘要');
      await page.locator(`[data-card="${i}"][data-prop="url"]`).fill('https://example.com/'+i);
    }
    await page.locator('[data-action="asset-up"][data-id="1"]').click();
    assert.equal(await page.locator('[data-card="0"][data-prop="title"]').inputValue(),'卡片 2');
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(dir,'workspace-composer-desktop.png'),fullPage:true,animations:'disabled'});
    await page.locator('#choose-composition').click();
    await page.locator('[data-select]').first().check();await page.locator('#review-button').click();
    assert.equal(await page.locator('.confirm-grid .line-card').count(),2);
    await page.route('**/api/send',route=>{payload=route.request().postDataJSON();return route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({job_id:payload.job_id})});});
    await page.locator('#send-timing').selectOption('scheduled');await page.locator('#scheduled-time').fill(future);
    await page.locator('#submit-send').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已建立預約'));
    assert.equal(payload.composition.format,'carousel');assert.equal(payload.composition.items[0].title,'卡片 2');
    assert(payload.scheduled_at);assert(!payload.composition.items[0].preview);assert(!payload.image_path);
    await page.locator('nav [data-view="send"]').click();
    await page.locator('[data-action="message-format"][data-id="imagemap"]').click();
    await page.locator('[data-action="map-layout"][data-id="six"]').click();
    for(let i=0;i<6;i++)await page.locator(`[data-area="${i}"]`).fill('https://example.com/area/'+i);
    assert.equal(await page.locator('.map-zones .map-region').count(),6);
    await page.locator('[data-action="map-region"][data-id="2"]').click();
    assert.equal(await page.locator('[data-area="2"]').evaluate(el=>el===document.activeElement),true);
    await page.locator('[data-action="map-layout"][data-id="four"]').focus();await page.keyboard.press('Enter');
    assert.equal(await page.locator('[data-area]').count(),4);
    assert.equal(await page.locator('.map-zones .map-region').count(),4);
    await page.locator('[data-action="map-layout"][data-id="six"]').click();
    assert.equal(await page.locator('[data-area="5"]').inputValue(),'https://example.com/area/5');
    await page.locator('[data-action="map-mode"][data-id="simulate"]').click();
    assert.equal(await page.locator('.map-zones b').count(),0);
    await page.locator('[data-action="map-region"][data-id="5"]').click();
    assert((await page.locator('.map-feedback').textContent()).includes('https://example.com/area/5'));
    await page.locator('[data-action="map-mode"][data-id="edit"]').click();
    await page.locator('.composer-grid').screenshot({path:path.join(dir,'imagemap-visual-preview.png'),animations:'disabled'});
    await page.setViewportSize({width:390,height:844});
    await page.waitForFunction(()=>document.querySelector('#sidebar').getBoundingClientRect().right<=1);
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(dir,'workspace-composer-mobile.png'),fullPage:true,animations:'disabled'});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile composer overflows');
    await page.locator('#choose-composition').click();await page.locator('[data-select]').first().check();await page.locator('#review-button').click();
    assert.equal(await page.locator('.confirm-grid .map-zones .map-region').count(),6);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile imagemap confirmation overflows');
    // The iOS-style drawer traps focus, closes with Escape/backdrop and restores the menu.
    await page.locator('#menu').click();
    assert(await page.locator('.workspace').evaluate(el=>el.inert));
    assert(await page.locator('#sidebar-close').evaluate(el=>el===document.activeElement));
    await page.keyboard.press('Shift+Tab');
    assert(await page.locator('#sidebar').evaluate(el=>el.contains(document.activeElement)));
    await page.keyboard.press('Tab');
    assert(await page.locator('#sidebar-close').evaluate(el=>el===document.activeElement));
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.workspace').evaluate(el=>el.inert),false);
    assert(await page.locator('#menu').evaluate(el=>el===document.activeElement));
    await page.locator('#menu').click();
    await page.locator('#nav-backdrop').click({position:{x:380,y:200}});
    assert.equal(await page.locator('#menu').getAttribute('aria-expanded'),'false');
    await page.locator('#menu').click();await page.locator('nav [data-view="reports"]').click();
    await page.locator('[data-action="new-report"]').click();
    const sheet=await page.locator('#modal').boundingBox();
    assert(Math.abs(sheet.y+sheet.height-844)<2,'Mobile sheet is not anchored to the bottom');
    const sheetHeader=await page.locator('.modal-head').boundingBox();
    const firstField=await page.locator('#report-form .field').first().boundingBox();
    assert(firstField.y>=sheetHeader.y+sheetHeader.height,'The sheet header obscures the first field');
    await page.screenshot({path:path.join(dir,'workspace-ios-sheet.png'),animations:'disabled'});
    await page.locator('#modal-close').click();
    await page.setViewportSize({width:768,height:1024});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Tablet layout overflows');
    await page.locator('#menu').click();await page.locator('nav [data-view="overview"]').click();
    await page.screenshot({path:path.join(dir,'workspace-ipad.png'),animations:'disabled'});
    assert.deepEqual(errors,[]);console.log(JSON.stringify({desktop:'passed',mobile:'passed',recipient_login:'blocked',sender_scopes:'passed',org_admin:'passed',remembered_preview:'passed',file_picker:'passed',carousel:'passed',imagemap:'passed',real_send_requests:0,browser_errors:0}));
  }finally{
    if(browser)await browser.close();fs.writeFileSync(stopFile,'stop');
    for(let i=0;i<50&&child.exitCode===null;i++)await delay(100);
    if(child.exitCode===null)child.kill();
    for(const file of [stateFile,stopFile])if(fs.existsSync(file))fs.unlinkSync(file);
  }
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
