"use strict";
const $ = id => document.getElementById(id);
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const paths = {grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',file:'<path d="M14 2H5v20h14V7zM14 2v6h5M8 12h8M8 16h6"/>',send:'<path d="m22 2-7 20-4-9-9-4zM11 13 22 2"/>',users:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 4a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 5v2"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M9 21h6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',settings:'<path d="M3 7h18M3 17h18"/><rect x="6" y="4" width="4" height="6" rx="1"/><rect x="14" y="14" width="4" height="6" rx="1"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',refresh:'<path d="M20 7a9 9 0 1 0 1 8M20 2v6h-6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',plus:'<path d="M12 4v16M4 12h16"/>',image:'<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8" cy="8" r="1"/><path d="m3 17 6-6 4 4 3-3 5 5"/>',check:'<path d="m5 12 4 4L19 6"/>',shield:'<path d="m12 2 8 3v6c0 6-8 11-8 11S4 17 4 11V5zM8 12l3 3 5-6"/>'};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.file}</svg>`;
document.querySelectorAll("[data-icon]").forEach(el => {el.innerHTML=icon(el.dataset.icon);});
const remote = location.hostname !== "127.0.0.1";
const token = remote ? "" : location.hash.slice(1) || sessionStorage.getItem("lineAdminToken") || "";
if(location.hash){if(!remote)sessionStorage.setItem("lineAdminToken",token);history.replaceState(null,"",location.pathname+location.search);}
$("logout").hidden=!remote;
const state={session:null,view:new URLSearchParams(location.search).get("view")||"overview",reports:[],contacts:[],jobs:[],settings:{users:[]},events:[],previews:new Map(),selected:new Set(),report:null,step:1,audience:"selected",search:"",kind:"all",company:"",department:"",page:1,reportFilter:"all",historyFilter:"all",subFilter:"all",busy:false,loaded:false,authLost:false};
const titles={overview:"工作總覽",reports:"報告中心",send:"建立發送",contacts:"收件者管理",subscriptions:"天氣訂閱",history:"發送紀錄",settings:"帳號與設定",organizations:"組織管理"};
const admin=()=>["administrator","company_admin","sender"].includes(state.session?.role);
const manager=()=>["administrator","company_admin"].includes(state.session?.role);
const canSend=()=>admin()&&Boolean(state.session?.modules?.messaging);
const superAdmin=()=>state.session?.role==="administrator";
const roleName=role=>({administrator:"平台管理員",company_admin:"組織管理員",sender:"發送人員",employee:"一般收件者（無後台資格）"}[role]||role);
const weatherModule=()=>superAdmin()&&state.reports.some(r=>r.report_id==="weather");
let viewAs="",viewKey="",viewOptions=[],principalSession=null,organization="",previewOrganization="",organizationKey="";
const orgName=id=>(state.organizations||[]).find(o=>o.org_id===id)?.name||id||"未指定組織";
const orgKinds={company:"公司",unit:"單位",association:"社團",club:"俱樂部",family:"家庭",personal:"個人工作室",other:"其他"};
const label=r=>r.alias||r.display_name||(r.kind==="user"?"未命名個人":"未命名群組");
const when=value=>value?new Date(value).toLocaleString("zh-TW",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}):"尚未產生";
const badge=(text,tone="")=>`<span class="badge ${tone}">${esc(text)}</span>`;
const button=(text,action,cls="",attrs="")=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const empty=(title,text)=>`<div class="empty">${icon("file")}<h3>${esc(title)}</h3><p>${esc(text)}</p></div>`;
const field=(text,name,value="",attrs="")=>`<label class="field">${esc(text)}<input name="${name}" value="${esc(value)}" ${attrs}></label>`;
const options=(items,value)=>items.map(([v,t])=>`<option value="${esc(v)}" ${v===value?"selected":""}>${esc(t)}</option>`).join("");
const selectField=(text,name,items,value)=>`<label class="field">${esc(text)}<select name="${name}">${options(items,value)}</select></label>`;
const person=r=>`<div class="person"><span class="avatar ${r.kind!=="user"?"group":""}">${esc(label(r).slice(0,1))}</span><div><strong>${esc(label(r))}</strong><small>${r.kind==="user"?"個人聊天室":"群組聊天室"}${!r.active?" · 已停用":""}</small></div></div>`;
const scope=r=>r.category==="composition"?(r.company?orgName(r.company):"平台個人素材"):r.scope==="module"?"天氣模組（依帳號／組織授權）":r.category==="text"?"自訂文字訊息":r.scope==="all"?"所有登入使用者":r.scope==="personal"?`${orgName(r.company)} · 個人專屬`:r.scope==="department"?`${orgName(r.company)} / ${r.department}`:`${orgName(r.company)} · 全組織`;
const reportBadge=r=>r.status!=="ready"?badge(r.status==="missing"?"等待報告":"無法使用","bad"):r.stale?badge("非今日更新","warn"):badge(admin()?"可發送":"可查看","good");
function notice(message,error=false){$("notice").textContent=message;$("notice").className="notice"+(error?" error":"");$("notice").hidden=!message;}
async function api(path,payload,original=false,root=false){
  const headers={"Content-Type":"application/json"};if(!remote)headers.Authorization=`Bearer ${token}`;
  if(organization&&!root)headers['X-Workspace-Organization']=encodeURIComponent(organization);
  if(viewAs&&!original&&!root){headers['X-Workspace-View-As']=viewAs;if(previewOrganization)headers['X-Workspace-Preview-Organization']=encodeURIComponent(previewOrganization);}
  let response;
  try{response=await fetch(path,{method:payload===undefined?"GET":"POST",headers,credentials:"same-origin",redirect:"error",cache:"no-store",body:payload===undefined?undefined:JSON.stringify(payload)});}
  catch(_){throw new Error("連線中斷或登入已逾時。請重新整理登入；發送中的工作請先查紀錄，避免重複發送。");}
  if(!response.headers.get("Content-Type")?.includes("application/json")){state.authLost=true;throw new Error("登入已逾時，請重新整理並登入。");}
  const result=await response.json();
  if(!response.ok){const error=new Error(result.error||"操作未完成。");error.status=response.status;if(response.status===401)state.authLost=true;throw error;}
  return result;
}
async function load(){
  const rootSession=await api("/api/session",undefined,true,true);
  organizationKey="lineWorkspaceOrganization:"+rootSession.identity;
  let remembered="";try{remembered=localStorage.getItem(organizationKey)||"";}catch(_){}
  const memberOptions=rootSession.memberships||[];
  organization=rootSession.role==="administrator"?"":(memberOptions.some(m=>m.org_id===remembered)?remembered:(rootSession.user.company||""));
  principalSession=organization?await api("/api/session",undefined,true):rootSession;
  $("organization-select").hidden=rootSession.role==="administrator"||!memberOptions.length;
  $("organization-select").innerHTML=options(memberOptions.map(m=>[m.org_id,m.name+" · "+roleName(m.role)]),organization);
  viewKey="lineWorkspaceView:"+principalSession.identity+":"+organization;
  viewOptions=["administrator","company_admin"].includes(principalSession.role)?(await api("/api/view-options",undefined,true)).users:[];
  let saved="";try{saved=localStorage.getItem(viewKey)||"";}catch(_){}
  const chosen=viewOptions.find(user=>user.email+"|"+user.company===saved);
  viewAs=chosen?.email||"";previewOrganization=chosen?.company||"";
  if(saved&&!viewAs){try{localStorage.removeItem(viewKey);}catch(_){}notice("已返回原帳號：先前預覽的成員資格已失效。",true);}
  state.session=viewAs?await api("/api/session"):principalSession;
  const orgData=await api("/api/organizations");state.organizations=orgData.organizations;state.memberships=orgData.memberships;
  $("switch-view").hidden=!["administrator","company_admin"].includes(principalSession.role);
  $("view-banner").hidden=!state.session.preview;
  $("view-description").textContent=state.session.preview?`角色視角：${roleName(state.session.role)} · ${state.session.user.display_name||viewAs}（${viewAs} · ${orgName(state.session.user.company)}） · 實際登入：${principalSession.identity}`:"";
  $("account-name").textContent=state.session.user?.display_name||state.session.identity;
  $("account-role").textContent=(state.session.preview?"預覽 · ":"")+roleName(state.session.role)+(state.session.user?.company?" · "+orgName(state.session.user.company):"");
  $("avatar").textContent=($("account-name").textContent||"L").slice(0,1).toUpperCase();
  document.querySelectorAll("[data-admin]").forEach(el=>{el.hidden=!admin();});document.querySelectorAll("[data-platform]").forEach(el=>{el.hidden=!superAdmin();});
  const reportResult=await api("/api/reports");state.reports=reportResult.reports;
  if(admin()){
    const results=await Promise.all([api("/api/contacts"),api("/api/jobs"),(manager()?api("/api/settings"):Promise.resolve({users:[]})),api("/api/activity")]);
    state.contacts=results[0].contacts;state.jobs=results[1].jobs;state.settings=results[2];state.events=results[3].events;
    state.selected=new Set([...state.selected].filter(id=>state.contacts.some(r=>r.recipient_id===id&&r.active)));
  }else{state.contacts=[];state.jobs=[];state.events=[];state.settings={users:[]};state.selected.clear();}
  document.querySelector('nav [data-view="subscriptions"]').hidden=!weatherModule();
  document.querySelector('nav [data-view="send"]').hidden=!admin()||!state.session.modules.messaging;
  document.querySelector('nav [data-view="settings"]').hidden=!manager();
  document.querySelector(".sidebar-bottom .nav-label").hidden=!manager();
  if(state.view==="settings"&&!manager())state.view="overview";
  if(state.view==="organizations"&&!superAdmin())state.view="reports";
  state.loaded=true;state.authLost=false;$("connection").innerHTML='<span class="status-dot"></span>已連線';
  $("sync-time").textContent="最後更新 "+new Date().toLocaleTimeString("zh-TW",{hour12:false});
  $("nav-report-count").textContent=state.reports.length;
  if((!admin()&&!['overview','reports'].includes(state.view))||(state.view==="subscriptions"&&!weatherModule()))state.view="reports";
}
function heading(title,subtitle,actions="",eyebrow="WORKSPACE"){return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="heading-actions">${actions}</div></div>`;}
function tile(r){if(r.category==="composition")return composerPreview(r.draft);if(r.category==="text")return `<div class="message-preview">${esc(r.message_text)}</div>`;const saved=state.previews.get(r.report_id);return `<div class="preview-tile">${saved?.version===r.version&&saved.preview?`<img src="${saved.preview}" alt="${esc(r.title)} 預覽">`:`<div class="preview-empty">${icon(r.category==="weather"?"image":"file")}<span>${r.status==="ready"?"載入預覽…":esc(r.reason)}</span></div>`}</div>`;}
async function hydratePreviews(){
  const visible=state.view==="overview"?state.reports.slice(0,1):state.view==="reports"||(state.view==="send"&&state.step===1)?state.reports:[];
  for(const report of visible.filter(r=>r.status==="ready")){
    if(state.previews.get(report.report_id)?.version===report.version)continue;
    try{const result=await api('/api/reports/'+report.report_id);state.previews.set(report.report_id,result);
      document.querySelectorAll('[data-preview]').forEach(el=>{if(el.dataset.preview===report.report_id)el.innerHTML=tile(result);});
    }catch(_){document.querySelectorAll('[data-preview]').forEach(el=>{if(el.dataset.preview===report.report_id)el.innerHTML=empty("預覽暫時無法載入","按重新整理再次讀取。");});}
  }
}
function stat(title,value,unit,note,symbol){return `<div class="stat"><div class="stat-top">${title}${icon(symbol)}</div><div class="stat-value">${value}<span>${unit}</span></div><p class="stat-note">${note}</p></div>`;}
function quick(title,description,view,symbol){return `<button class="quick" data-view="${view}"><span class="quick-icon">${icon(symbol)}</span><span><strong>${title}</strong><small>${description}</small></span>${icon("arrow")}</button>`;}
function overview(){
  const ready=state.reports.filter(r=>r.status==="ready").length, active=state.contacts.filter(r=>r.active).length, subscribed=state.contacts.filter(r=>r.active&&r.weather_subscribed).length;
  const pending=state.jobs.filter(j=>["scheduled","queued","running"].includes(j.status)).length;
  const date=new Date().toLocaleDateString("zh-TW",{month:"long",day:"numeric",weekday:"long"});
  const r=state.reports[0];
  return heading(admin()?"今天的工作，一目了然":"你的報告，都在這裡",`${esc(date)}　·　${admin()?"檢查報告、安排收件對象，掌握每次發送結果。":"依照你的公司、部門與個人權限，查看最新內容。"}`,canSend()?button(icon("plus")+"建立發送","start-send","primary"):button("瀏覽報告 "+icon("arrow"),"go-reports","primary"),"YOUR DAILY WORKSPACE")+
    `<div class="stats">${stat("可用報告",ready,"份",`已登記 ${state.reports.length} 份報告`,"file")}${admin()?stat("有效收件者",active,"個",`${state.contacts.filter(r=>r.active&&r.kind!=="user").length} 個群組聊天室`,"users")+(weatherModule()?stat("天氣訂閱",subscribed,"個","發送時檢查最新訂閱狀態","bell"):stat("所屬組織",esc(state.session.user?.company||"—"),"","資料依公司隔離","shield"))+stat("進行中的發送",pending,"筆","結果不明的請求不自動重送","send"):stat("所屬部門",esc(state.session.user?.department||"未指定"),"","只顯示獲授權內容","shield")}</div>
    <div class="dashboard-grid"><div class="stack"><section class="panel"><div class="panel-head"><div><h2>報告焦點</h2><p>先確認內容，再開始下一步</p></div><button class="btn text small" data-view="reports">所有報告 ${icon("arrow")}</button></div>${r?`<div class="feature"><div data-preview="${esc(r.report_id)}">${tile(r)}</div><div>${reportBadge(r)}<h3>${esc(r.title)}</h3><p>最後更新　${when(r.modified_at)}</p><p>${esc(scope(r))}</p>${r.stale?'<p>此報告不是今日更新，發送前請確認。</p>':""}${button(canSend()?"預覽並建立發送 "+icon("arrow"):"開啟報告 "+icon("arrow"),canSend()?"choose-report":"preview","dark",`data-id="${esc(r.report_id)}" ${r.status!=="ready"?"disabled":""}`)}</div></div>`:empty("還沒有可用報告","管理員設定報告來源與權限後，就會顯示在這裡。")}</section>${admin()?`<section class="panel"><div class="panel-head"><h2>最近發送</h2><button class="btn text small" data-view="history">查看全部 ${icon("arrow")}</button></div>${historyList(state.jobs.slice(0,3))}</section>`:""}</div><div class="stack"><section class="panel"><div class="panel-head"><h2>快速前往</h2></div><div class="quick-list">${quick("報告中心","預覽獲授權的模組報告","reports","file")}${admin()?quick("收件者管理","整理公司、部門與群組","contacts","users")+(weatherModule()?quick("天氣訂閱","管理持續接收通知的對象","subscriptions","bell"):""):""}</div></section><aside class="insight"><h3>${icon("shield")}${admin()?"分對對象，送對報告":"你的資料範圍"}</h3><p>${admin()?"組織報表依公司、部門或個人範圍選擇收件者。一般收件者只需在 LINE 收訊；需要操作後台的發送人員才須登入授權。":"此處只列出你獲授權的報告。若缺少需要的內容，請聯絡管理員確認公司及部門設定。"}</p></aside></div></div>`;
}
function reportsPage(wizard=false){
  const rows=state.reports.filter(r=>state.reportFilter==="all"||r.category===state.reportFilter);
  return (wizard?"":heading("報告中心","預覽最新內容，依公司、部門與個人分配報告。",superAdmin()?(state.settings.weather_report_removed?button("恢復天氣報告","restore-weather",""):"")+button(icon("plus")+"新增報告來源","new-report","primary"):"","REPORT LIBRARY"))+
    `<div class="heading-actions section-space segmented">${[["all","所有報告"],...(state.reports.some(r=>r.category==="weather")?[["weather","天氣報告"]]:[]),["company","組織報表"],["other","其他報告"]].map(([id,text])=>`<button data-action="report-filter" data-id="${id}" class="${state.reportFilter===id?"active":""}">${text}</button>`).join("")}</div><div class="report-grid section-space">${rows.map(r=>`<article class="panel report-card"><div data-preview="${esc(r.report_id)}">${tile(r)}</div><div class="report-card-body">${reportBadge(r)}<h3>${esc(r.title)}</h3><div class="report-meta"><span>${esc(scope(r))}</span><span>${icon("clock")} ${when(r.modified_at)}${r.size?` · ${Math.ceil(r.size/1024)} KB`:""}</span></div><div class="report-card-bottom">${button("預覽","preview","",`data-id="${esc(r.report_id)}" ${r.status!=="ready"?"disabled":""}`)}${canSend()?button(wizard?"選擇這份報告":"建立發送","choose-report","primary",`data-id="${esc(r.report_id)}" ${r.status!=="ready"?"disabled":""}`):""}</div>${superAdmin()?`<div class="report-card-bottom">${r.report_id!=="weather"?button("設定來源","edit-report","text small",`data-id="${esc(r.report_id)}"`):""}${button("移除報告","remove-report","text small",`data-id="${esc(r.report_id)}"`)}</div>`:""}</div></article>`).join("")}</div>${rows.length?"":empty("這裡還沒有報告",admin()?"新增來源後，外部程式產生的 PNG 就會顯示在報告中心。":"管理員授權報告後，你就能在這裡查看。")}`;
}
function eligible(r){const source=state.report;if(source?.category==="composition")return !source.company||r.company===source.company;if(!source||source.category==="text"||source.report_id==="weather")return true;if(r.company!==source.company)return false;if(source.scope==="department")return r.department===source.department;if(source.scope==="personal")return source.owner_recipient_id?r.recipient_id===source.owner_recipient_id:(state.memberships||[]).some(m=>m.active&&m.org_id===source.company&&m.email===source.owner_email&&m.recipient_id===r.recipient_id)||state.settings.users.some(u=>u.active&&u.company===source.company&&u.email===source.owner_email&&u.recipient_id===r.recipient_id);return true;}
function filteredContacts(){return state.contacts.filter(r=>(!state.search||`${label(r)} ${r.display_name} ${r.company} ${r.department}`.toLowerCase().includes(state.search.toLowerCase()))&&(state.kind==="all"||(state.kind==="group"?r.kind!=="user":r.kind===state.kind))&&(!state.company||r.company===state.company)&&(!state.department||r.department===state.department)&&(state.view!=="send"||(r.active&&eligible(r)))&&(state.view!=="subscriptions"||state.subFilter==="all"||Boolean(r.weather_subscribed)===(state.subFilter==="on")));}
function contactToolbar(){const companies=[...new Set(state.contacts.map(r=>r.company).filter(Boolean))],depts=[...new Set(state.contacts.filter(r=>!state.company||r.company===state.company).map(r=>r.department).filter(Boolean))];return `<div class="toolbar"><label class="search-field">${icon("search")}<input id="contact-search" value="${esc(state.search)}" placeholder="搜尋名稱、公司或部門" aria-label="搜尋收件者"></label><select id="contact-kind" aria-label="聊天室類型">${options([["all","所有聊天室"],["user","個人"],["group","群組"]],state.kind)}</select><select id="contact-company" aria-label="篩選公司">${options([["","所有組織"],...companies.map(c=>[c,orgName(c)])],state.company)}</select><select id="contact-department" aria-label="篩選部門">${options([["","所有部門"],...depts.map(c=>[c,c])],state.department)}</select></div>`;}
function contactList(){const rows=filteredContacts(),pages=Math.max(1,Math.ceil(rows.length/10));state.page=Math.min(state.page,pages);const visible=rows.slice((state.page-1)*10,state.page*10),selecting=state.view==="send"&&state.audience==="selected";return `${selecting?`<div class="toolbar">${button("勾選本頁","select-page","small")}${button("清除勾選","clear-selection","text small")}<small class="muted">共 ${rows.length} 個符合報告範圍的聊天室</small></div>`:""}<div class="table-scroll"><table class="contacts-table"><thead><tr><th></th><th>收件者</th><th>組織／部門</th>${weatherModule()?"<th>天氣訂閱</th>":""}<th>操作</th></tr></thead><tbody>${visible.map(r=>`<tr><td class="select-cell">${selecting?`<input type="checkbox" data-select="${esc(r.recipient_id)}" aria-label="選取 ${esc(label(r))}" ${state.selected.has(r.recipient_id)?"checked":""}>`:""}</td><td class="person-cell">${person(r)}</td><td class="meta-cell">${esc(r.company?orgName(r.company):"尚未分類")}<small class="muted">${r.department?" / "+esc(r.department):""}</small></td>${weatherModule()?`<td class="sub-cell">${badge(r.weather_subscribed?"已訂閱":"未訂閱",r.weather_subscribed?"good":"")}</td>`:""}<td class="action-cell">${manager()?button("管理","edit-contact","small",`data-id="${esc(r.recipient_id)}"`):badge("已授權")}</td></tr>`).join("")}</tbody></table></div>${!rows.length?empty("沒有符合的收件者",state.view==="send"?"請確認收件者的組織／部門分類符合報告範圍，並已與 Bot 互動。":"調整篩選條件，或請使用者向 Bot 傳送訊息以建立名單。"):""}<div class="pagination"><span>共 ${rows.length} 個聊天室</span><div>${button("上一頁","prev-page","small",state.page<=1?"disabled":"")}<span>${state.page} / ${pages}</span>${button("下一頁","next-page","small",state.page>=pages?"disabled":"")}</div></div>`;}
function contactsPage(subscriptions=false){return heading(subscriptions?"天氣訂閱":"收件者管理",subscriptions?"訂閱決定持續接收通知的對象；每次發送仍由管理員確認。":"依公司與部門整理個人、群組，讓報告送到正確的地方。",(manager()?button(icon("refresh")+"更新 LINE 名稱","profiles"):""),subscriptions?"SUBSCRIPTIONS":"CONTACT DIRECTORY")+(subscriptions?`<div class="insight"><h3>${icon("bell")}個人自行訂閱，群組由管理員設定</h3><p>私訊 Bot「訂閱天氣」「取消訂閱」「我的訂閱」即可管理個人訂閱。目前由管理員發送，可指定單次傳送時間，尚未啟用每日循環排程。</p></div><div class="segmented section-space">${[["all","全部"],["on","已訂閱"],["off","未訂閱"]].map(([id,t])=>`<button data-action="sub-filter" data-id="${id}" class="${state.subFilter===id?"active":""}">${t}</button>`).join("")}</div>`:"")+`<section class="panel section-space">${contactToolbar()}<div id="contact-list">${contactList()}</div></section>`;}
function selectedRows(){return state.contacts.filter(r=>r.active&&eligible(r)&&(state.audience==="subscribers"?r.weather_subscribed:state.selected.has(r.recipient_id)));}
function selectionSummary(){const rows=selectedRows();return `<div class="panel selection-summary"><div class="panel-body">${tile(state.report)}<p class="eyebrow section-space">THIS DELIVERY</p><h3>${esc(state.report.title)}</h3><p class="subtitle">${esc(scope(state.report))}</p><div class="count-big">${rows.length}<small>個聊天室</small></div><div class="summary-list">${rows.map(r=>`<span>${esc(label(r))}</span>`).join("")||'<small class="muted">請從名單選擇收件者</small>'}</div><p class="callout">每個聊天室會收到這次確認的內容。一次性勾選不會改變訂閱設定。</p></div></div>`;}
function sendPage(){const r=state.report;return heading("建立發送","依序確認報告、對象與內容，每次發送都有完整紀錄。","","NEW DELIVERY")+`<div class="steps">${["編輯內容","選擇對象","確認發送"].map((t,i)=>`${i?'<span class="step-line"></span>':""}<span class="step ${state.step===i+1?"active":""}"><b>${i+1}</b>${t}</span>`).join("")}</div>`+(state.step===1||!r?composerEditor()+`<section class="panel panel-body section-space"><h2>文字訊息</h2><p class="subtitle">輸入公告或提醒，下一步選擇收件者與傳送時間。</p><textarea id="message-draft" maxlength="5000" rows="5" placeholder="輸入要傳送的文字">${esc(state.textDraft||"")}</textarea><div class="form-actions">${button("使用這段文字","choose-text","primary")}</div></section>`+reportsPage(true):state.step===2?`<div class="send-grid"><section class="panel"><div class="panel-head"><div><h2>這次要發給誰？</h2><p>僅列出符合報告組織／部門／個人範圍的有效收件者</p></div></div>${r.report_id==="weather"?`<div class="toolbar segmented">${[["selected","手動選擇"],["subscribers","天氣訂閱名單"]].map(([id,t])=>`<button data-action="audience" data-id="${id}" class="${state.audience===id?"active":""}">${t}</button>`).join("")}</div>`:""}${state.audience==="selected"?contactToolbar()+`<div id="contact-list">${contactList()}</div>`:`<div class="panel-body"><p class="callout">目前有 ${selectedRows().length} 個有效天氣訂閱。發送時會再次檢查訂閱狀態，尚未送出的取消訂閱會自動排除。</p></div>`}<div class="selection-footer">${button("返回編輯","back-report")}${button("下一步：確認發送 "+icon("arrow"),"review","primary",`id="review-button" ${selectedRows().length?"":"disabled"}`)}</div></section><aside id="selection-summary">${selectionSummary()}</aside></div>`:confirmation());}
function confirmation(){const r=state.report,rows=selectedRows();return `<section class="panel"><div class="panel-head"><h2>確認這次的發送內容</h2>${reportBadge(r)}</div><div class="panel-body confirm-grid"><div>${["text","composition"].includes(r.category)?tile(r):`<img class="confirm-preview" src="${r.preview}" alt="${esc(r.title)} 完整預覽"><p class="subtitle">內容更新時間：${when(r.modified_at)}</p>`}</div><div><p class="eyebrow">DELIVERY SUMMARY</p><h2>${esc(r.title)}</h2><div class="detail-row"><span>發送方式</span><strong>${state.audience==="subscribers"?"天氣訂閱名單":"手動選擇"}</strong></div><div class="detail-row"><span>收件聊天室</span><strong>${rows.length} 個（${rows.filter(x=>x.kind==="user").length} 個人／${rows.filter(x=>x.kind!=="user").length} 群組）</strong></div><div class="detail-row"><span>操作人</span><strong>${esc(state.session.identity)}</strong></div><div class="summary-list">${rows.map(x=>`<span>${esc(label(x))}</span>`).join("")}</div><p class="callout">送出前會再次檢查報告版本與收件範圍。LINE 已接受代表 API 受理，不代表收件者已讀。</p>${scheduleFields()}${r.stale?'<p class="callout warn">這份報告不是今天更新。請確認日期與內容適用於這次發送。</p><label class="check-label"><input id="allow-stale" type="checkbox">我已確認，可以發送這份較早的報告</label>':""}<div class="form-actions">${button("上一步","back-recipients")}${button(icon("send")+`確認發送給 ${rows.length} 個聊天室`,"submit-send","primary",`id="submit-send" ${state.busy||!rows.length?"disabled":""}`)}</div></div></div></section>`;}
const statusNames={scheduled:"已預約",missed:"預約逾期／未發送",queued:"排隊中",running:"發送中",finished:"工作完成",interrupted:"工作中斷",pending:"等待發送",sending:"正在發送",accepted:"LINE 已接受",failed:"發送失敗",unknown:"狀態不明",cancelled:"未發送／已取消"};
function jobTone(job){return job.deliveries.some(d=>["failed","unknown"].includes(d.status))?"bad":job.status==="finished"?"good":"warn";}
function historyList(jobs){return jobs.length?jobs.map(j=>`<details class="history-item" data-job="${esc(j.job_id)}"><summary><span class="history-title"><strong>${esc(j.report_title||"手動圖片發送")}</strong><small>${when(j.created_at)} · ${esc(j.actor||"舊版未記錄操作人")}</small></span>${badge(`${j.deliveries.filter(d=>d.status==="accepted").length} / ${j.deliveries.length} 已接受`,jobTone(j))}${badge(statusNames[j.status]||j.status)}</summary><div class="job-detail">${j.scheduled_at?`<p class="callout">預約時間：${scheduleLabel(j.scheduled_at)}（台北時間）</p>`:""}${j.message_text?`<div class="message-preview">${esc(j.message_text)}</div>`:""}${j.status==="scheduled"?button("取消預約","cancel-schedule","danger",`data-id="${esc(j.job_id)}"`):""}${j.error?`<p class="callout warn">${esc(j.error)}</p>`:""}${j.deliveries.map(d=>`<div class="delivery"><span>${esc(d.label)}</span>${badge(statusNames[d.status]||d.status,d.status==="accepted"?"good":["failed","unknown"].includes(d.status)?"bad":"")}${d.error?`<small>${esc(d.error)}</small>`:""}</div>`).join("")}<p class="callout">發送失敗或狀態不明時，請先確認聊天室與 LINE 設定，再決定是否建立新的發送工作。</p><small class="contact-id">工作 ${esc(j.job_id)}</small></div></details>`).join(""):empty("還沒有發送紀錄","完成第一次發送後，可以在這裡查看每個聊天室的結果。");}
function historyPage(){const rows=state.jobs.filter(j=>state.historyFilter==="all"||(state.historyFilter==="issues"?(j.status==="missed"||j.deliveries.some(d=>["unknown","failed"].includes(d.status))):['scheduled','queued','running'].includes(j.status)));return heading("發送紀錄","逐筆確認結果。API 已接受不代表已讀；異常工作不會自動重送。",button("建立發送","start-send","primary"),"DELIVERY HISTORY")+`<section class="panel"><div class="toolbar segmented">${[["all","預約與最近紀錄"],["issues","需要處理"],["active","進行中"]].map(([id,t])=>`<button data-action="history-filter" data-id="${id}" class="${state.historyFilter===id?"active":""}">${t}</button>`).join("")}</div><div id="history-list">${historyList(rows)}</div></section>`;}
function settingsPage(){const s=state.settings;return heading("帳號與設定","管理登入身分與資料範圍，讓團隊各自取得需要的報告。",(superAdmin()?button(icon("plus")+"新增帳號","new-account","primary"):""),"WORKSPACE SETTINGS")+`<div class="settings-grid"><div class="stack"><section class="panel settings-users"><div class="panel-head"><h2>登入帳號</h2>${badge(s.users.length+" 個帳號")}</div><div class="panel-body">${s.users.map(u=>`<div class="detail-row"><div><strong>${esc(u.display_name||u.email)}</strong><p class="subtitle">${esc(u.email)}<br>${esc([u.company?orgName(u.company):"",u.department].filter(Boolean).join(" / ")||"未指定組織／部門")}</p></div><div>${badge(roleName(u.role),u.active?"good":"")}${!u.active?badge("已停用","bad"):""} ${superAdmin()?button("編輯","edit-account","small",`data-id="${esc(u.email)}"`):""}</div></div>`).join("")}<p class="callout">新增帳號後，還需在 Cloudflare Access 的允許原則加入同一信箱。一般收件者不需後台帳號。發送人員建立後，請至組織管理設定授權範圍、模組與報告；未授權預設不可發送。</p></div></section><section class="panel"><div class="panel-head"><h2>最近操作</h2><small class="muted">最近 50 筆</small></div><div class="panel-body">${state.events.map(e=>`<div class="activity-row">${esc(e.detail)}<small>${esc(e.actor)} · ${when(e.created_at)}</small></div>`).join("")||'<p class="muted">尚無新版操作紀錄。</p>'}</div></section></div><div class="stack"><section class="panel"><div class="panel-head"><h2>整合狀態</h2></div><div class="panel-body"><div class="detail-row"><span>LINE 發送憑證</span>${badge(s.line_configured?"已設定":"未設定",s.line_configured?"good":"bad")}</div><div class="detail-row"><span>Cloudflare Access</span>${badge(s.remote_enabled?"已設定":"僅限本機",s.remote_enabled?"good":"warn")}</div><div class="detail-row"><span>管理網址</span><strong>${esc(s.admin_host||"—")}</strong></div><p class="callout">此處顯示本機設定狀態。公開連線與服務啟停可從電腦上的 LINE 控制台檢查。</p></div></section><aside class="insight"><h3>${icon("shield")}資料權限在後端檢查</h3><p>部門與公司名稱需一致。個人報告直接指定 LINE 收件者，不需要建立登入帳號。發送人員僅能使用獲授權的報告與收件範圍。</p></aside></div></div>`;}
function render(){
  if(!titles[state.view]||(state.view==="settings"&&!manager())||(state.view==="organizations"&&!superAdmin()))state.view="overview";
  if((!admin()&&!['overview','reports'].includes(state.view))||(state.view==="subscriptions"&&!weatherModule()))state.view="reports";
  $("crumb").textContent=titles[state.view];document.title=titles[state.view]+" · LINE 自動化";
  document.querySelectorAll("nav [data-view]").forEach(el=>{const current=el.dataset.view===state.view;el.classList.toggle("active",current);if(current)el.setAttribute("aria-current","page");else el.removeAttribute("aria-current");});
  const pages={overview,reports:reportsPage,send:sendPage,contacts:()=>contactsPage(false),subscriptions:()=>contactsPage(true),history:historyPage,settings:settingsPage,organizations:organizationsPage};
  $("page").innerHTML=pages[state.view]();hydratePreviews();
}
function navigate(view){if(state.busy)return;notice("");state.view=view;state.search="";state.kind="all";state.company="";state.department="";state.page=1;setSidebarOpen(false);history.replaceState(null,"","/?view="+encodeURIComponent(view));render();window.scrollTo({top:0});}
function modal(title,html){$("modal-title").textContent=title;$("modal-body").innerHTML=html;$("modal-error").hidden=true;if(!$("modal").open)$("modal").showModal();$("modal").scrollTop=0;$("modal-close").focus({preventScroll:true});}
function editContact(id){const r=state.contacts.find(x=>x.recipient_id===id);modal("管理收件者",`<form id="contact-form" data-id="${esc(id)}"><div class="form-grid">${field("備註名稱","alias",r.alias,'maxlength="80"')}${(superAdmin()?selectField("組織","company",organizationOptions(),r.company):field("組織","organization_label",orgName(r.company),'readonly')+`<input type="hidden" name="company" value="${esc(r.company)}">`)}${field("部門","department",r.department,'maxlength="60" placeholder="例如：業務部"')}${weatherModule()?`<label class="check-label"><input name="subscribed" type="checkbox" ${r.weather_subscribed?"checked":""} ${r.active?"":"disabled"}>接收天氣通知</label>`:""}</div><p class="callout">組織／部門決定可以收到哪些報表。${r.kind==="user"?"個人也能透過 Bot 自行訂閱天氣。":"群組天氣訂閱由管理員設定。"}</p><details><summary class="muted">查看聊天室識別資料</summary><p class="contact-id">${esc(id)}</p></details><div class="form-actions"><button class="btn primary" type="submit">儲存收件者</button></div></form>`);}
function reportForm(reportId){const source=(state.settings.report_sources||[]).find(r=>r.report_id===reportId);modal(source?"編輯報告來源":"新增報告來源",`<form id="report-form"><div class="form-grid">${field("報告名稱","title","",'required maxlength="80" placeholder="例如：每日業績報表"')}${selectField("報告類型","category",[["company","組織報表"],["weather","天氣報告"],["other","其他報告"]],"company")}${selectField("組織","company",organizationOptions(),"")}${selectField("可見範圍","scope",[["company","全組織"],["department","指定部門"],["personal","指定個人"]],"company")}${field("部門（部門報告必填）","department","",'maxlength="60"')}${selectField("LINE 個人收件者（個人報告必填）","owner_recipient_id",[["","選擇收件者"],...state.contacts.filter(r=>r.kind==="user"&&r.active).map(r=>[r.recipient_id,label(r)+" · "+orgName(r.company)])],"")}<div class="full"><input name="asset_id" type="hidden"><label class="upload-picker">${icon("image")}<strong>從裝置選擇報告圖片</strong><span>JPG／PNG，每張最多 8 MB</span><input id="report-file" type="file" accept="image/png,image/jpeg,.jpg,.jpeg,.png"></label><div id="report-upload-preview" role="status"></div><p class="subtitle">先選組織再上傳；保存本次檔案的副本。每日自動更新的報告可使用下方進階設定。</p><details><summary>進階設定：自動化報告來源</summary><label class="field section-space">伺服器 PNG 路徑<input name="source_path" placeholder="D:\\Reports\\daily.png"><small>外部程式更新此檔案後，報告中心會讀取最新版。目前支援 1 MB 以內 PNG。</small></label></details></div></div><div class="form-actions"><button class="btn primary" type="submit">儲存報告來源</button></div></form>`);if(source){const form=$("report-form");form.dataset.id=source.report_id;for(const key of ["title","category","company","scope","department","owner_recipient_id","source_path"])form.elements[key].value=source[key]||"";if(!source.owner_recipient_id&&source.owner_email)form.elements.owner_recipient_id.value=state.memberships.find(m=>m.email===source.owner_email&&m.org_id===source.company)?.recipient_id||"";}}
function accountForm(email){const u=state.settings.users.find(x=>x.email===email)||{email:"",display_name:"",role:"sender",company:"",department:"",recipient_id:"",active:1};modal(email?"編輯登入帳號":"新增登入帳號",`<form id="account-form"><div class="form-grid">${field("Email","email",u.email,`type="email" required ${email?"readonly":""}`)}${field("顯示名稱","display_name",u.display_name,'maxlength="80"')}${selectField("角色","role",[["sender","發送人員：依授權範圍發送"],["employee","一般收件者：停用後台登入（保留舊資料）"],["company_admin","組織管理員：所屬組織模組與發送"],["administrator","平台管理員：全部組織及個人模組"]],u.role)}${selectField("主要組織（非平台管理員必填）","company",organizationOptions(),u.company)}${field("部門","department",u.department,'maxlength="60"')}${selectField("對應個人 LINE 聊天室","recipient_id",[["","暫不連結"],...state.contacts.filter(r=>r.kind==="user").map(r=>[r.recipient_id,label(r)+" · "+(r.company||"未分類")])],u.recipient_id)}<label class="check-label full"><input name="active" type="checkbox" ${u.active?"checked":""}>啟用此帳號</label></div><p class="callout warn">儲存後，請到 Cloudflare Access 允許原則加入這個 Email，才能通過登入入口。一般收件者不需新增帳號。發送人員需再到「組織管理」設定發送授權，預設沒有模組或收件範圍。</p><div class="form-actions"><button class="btn primary" type="submit">儲存帳號</button></div></form>`);}
async function chooseReport(id){if(!state.session.modules.messaging)throw new Error("此組織未授權訊息發送模組。");if(sessionStorage.getItem("linePendingJob"))throw new Error("請先確認上次發送的狀態，再建立新的工作。");const r=await api('/api/reports/'+id);if(r.status!=="ready")throw new Error(r.reason);state.report=r;state.previews.set(id,r);state.step=2;state.selected.clear();state.audience="selected";navigate("send");}
async function submitSend(){
  if(state.busy)return;
  if(!state.session.modules.messaging)throw new Error("此組織未授權訊息發送模組。");
  if(state.session.preview)throw new Error("預覽不會實際發送，請返回原帳號操作。");
  if(sessionStorage.getItem("linePendingJob"))throw new Error("有一筆提交尚未確認。請先到發送紀錄檢查，再重新整理。");
  const allow=Boolean($("allow-stale")?.checked);if(state.report.stale&&!allow)throw new Error("請先確認這份較早的報告仍適合發送。");
  const id=crypto.randomUUID(),payload={job_id:id,allow_stale:allow,audience:state.audience,ids:selectedRows().map(r=>r.recipient_id)};
  if(state.report.category==="composition")payload.composition=state.report.composition;else if(state.report.category==="text")payload.message_text=state.report.message_text;else{payload.report_id=state.report.report_id;payload.report_version=state.report.version;}
  if($("send-timing").value==="scheduled"){const value=$("scheduled-time").value;const date=new Date(value+":00+08:00");if(!value||!Number.isFinite(date.getTime())||date.getTime()<Date.now()+30000)throw new Error("請選擇至少 30 秒後的台北時間。");payload.scheduled_at=date.toISOString();}
  state.busy=true;sessionStorage.setItem("linePendingJob",id);$("submit-send").disabled=true;$("submit-send").textContent="正在驗證並建立工作…";
  try{await api("/api/send",payload);sessionStorage.removeItem("linePendingJob");state.busy=false;await load();state.step=1;state.report=null;state.selected.clear();navigate("history");notice(payload.scheduled_at?"已建立預約，可於發送紀錄查看或取消。":"發送工作已建立，可以展開紀錄查看每個聊天室的結果。");const el=document.querySelector(`[data-job="${id}"]`);if(el)el.open=true;}
  catch(error){state.busy=false;if(error.status&&error.status<500)sessionStorage.removeItem("linePendingJob");render();throw error;}
}
async function recoverSubmission(){const id=sessionStorage.getItem("linePendingJob");if(!id||!admin())return;try{const result=await api('/api/jobs/'+id);if(result.jobs.length){sessionStorage.removeItem("linePendingJob");notice("上次提交已建立工作，請查看發送紀錄。",false);}}catch(error){if(error.status===404){notice("上次提交尚無紀錄；可能仍在處理。請稍後重新整理確認，避免重複發送。",true);modal("確認上次發送",`<p>伺服器目前找不到上次工作紀錄。請先確認聊天室沒有收到圖片，且原本的提交已結束，再解除保護。</p><p class="contact-id section-space">工作 ${esc(id)}</p><div class="form-actions">${button("我已確認，解除提交保護","clear-pending","danger")}</div>`);}else throw error;}}
function viewPicker(){
  modal("切換檢視視角",`<p class="subtitle">目前登入：${esc(principalSession.identity)}。預覽會套用該帳號的角色、公司、部門與個人資料權限，並禁止寫入操作。</p><div class="view-options">${button("返回原帳號視角","apply-view","",'data-id=""')}${viewOptions.map(user=>button(`<strong>${esc(user.display_name||user.email)}</strong><small>${esc(user.email)} · ${esc(roleName(user.role))} · ${esc(user.organization_name||orgName(user.company))} / ${esc(user.department||"未分部門")}</small>`,"apply-view",user.email===viewAs&&user.company===previewOrganization?"active":"",`data-id="${esc(user.email+"|"+user.company)}"`)).join("")}</div>${!viewOptions.length?'<p class="callout">目前沒有可預覽的帳號；平台管理員可在「帳號與設定」新增或調整角色。</p>':""}<p class="subtitle">本瀏覽器會記住選擇；預覽不會變更真正的登入帳號。Cloudflare 登入到期後仍需驗證。</p>`);
}
function switchView(email){
  if(email&&!viewOptions.some(user=>user.email+"|"+user.company===email))throw new Error("請重新整理可用帳號。");
  if(email)localStorage.setItem(viewKey,email);else localStorage.removeItem(viewKey);
  // A full navigation discards in-flight previews and all previous-role data.
  location.replace(location.pathname+"?view="+(email?"reports":"overview"));
}
document.addEventListener("click",async event=>{
  const nav=event.target.closest("[data-view]");if(nav){navigate(nav.dataset.view);return;}
  const target=event.target.closest("[data-action]");if(!target||target.disabled||state.busy)return;
  const action=target.dataset.action,id=target.dataset.id;
  try{
    if(composerAction(action,id))return;
    if(action==="new-organization")organizationForm();
    else if(action==="edit-organization")organizationForm(id);
    else if(action==="new-membership")membershipForm();
    else if(action==="edit-membership")membershipForm(id);
    else if(action==="switch-view")viewPicker();
    else if(action==="apply-view")switchView(id||"");
    else if(action==="go-reports")navigate("reports");
    else if(action==="start-send"){state.step=1;state.report=null;state.reportFilter="all";navigate("send");}
    else if(action==="choose-text"){const text=$("message-draft").value;if(!text.trim())throw new Error("請先輸入文字。");if(sessionStorage.getItem("linePendingJob"))throw new Error("請先確認上次提交結果。");state.textDraft=text;state.report={category:"text",title:"文字訊息",message_text:text,status:"ready",scope:"text"};state.step=2;state.selected.clear();state.audience="selected";render();}
    else if(action==="cancel-schedule")modal("取消這筆預約？",`<p>取消後不會傳送。已開始處理的工作無法取消。</p><div class="form-actions">${button("確認取消預約","confirm-cancel-schedule","danger",`data-id="${esc(id)}"`)}</div>`);
    else if(action==="confirm-cancel-schedule"){await api('/api/jobs/cancel',{job_id:id});$("modal").close();await load();render();notice("預約已取消。");}
    else if(action==="choose-report")await chooseReport(id);
    else if(action==="preview"){const r=await api('/api/reports/'+id);if(r.status!=="ready")throw new Error(r.reason);modal(r.title,`<img class="modal-preview" src="${r.preview}" alt="${esc(r.title)}"><p class="subtitle">${when(r.modified_at)} · ${esc(scope(r))}</p>${r.stale?'<p class="callout warn">非今日更新，請留意資料日期。</p>':""}${admin()?`<div class="form-actions">${button("使用這份報告","preview-send","primary",`data-id="${esc(id)}"`)}</div>`:""}`);}
    else if(action==="preview-send"){$("modal").close();await chooseReport(id);}
    else if(action==="new-report")reportForm();
    else if(action==="edit-report"){reportForm(id);$("report-form").insertAdjacentHTML("beforeend",button("移除這個報告來源","remove-report","text small",`data-id="${esc(id)}" type="button"`));}
    else if(action==="remove-report")modal("移除報告來源",`<p>將從報告中心移除「${esc(state.reports.find(r=>r.report_id===id)?.title)}」。原始圖片與既有發送紀錄會保留，尚未開始的發送工作會取消；已開始或已送出的訊息無法撤回。${id==="weather"?"此設定對所有組織生效；之後可在報告中心恢復天氣報告。":""}</p><div class="form-actions">${button("確認移除","confirm-remove-report","danger",`data-id="${esc(id)}"`)}</div>`);
    else if(action==="confirm-remove-report"){await api('/api/reports/remove',{report_id:id});$("modal").close();state.reportFilter="all";state.report=null;await load();render();notice("報告來源已移除，尚未開始的發送工作已取消。");}
    else if(action==="restore-weather"){await api("/api/reports/restore-weather",{});state.reportFilter="all";await load();render();notice("天氣報告已恢復；已取消的發送不會恢復。");}
    else if(action==="report-filter"){state.reportFilter=id;render();}
    else if(action==="sub-filter"){state.subFilter=id;state.page=1;render();}
    else if(action==="history-filter"){state.historyFilter=id;render();}
    else if(action==="prev-page"||action==="next-page"){state.page+=action==="next-page"?1:-1;$("contact-list").innerHTML=contactList();}
    else if(action==="select-page"){filteredContacts().slice((state.page-1)*10,state.page*10).forEach(r=>state.selected.add(r.recipient_id));updateSelection();}
    else if(action==="clear-selection"){state.selected.clear();updateSelection();}
    else if(action==="edit-contact")editContact(id);
    else if(action==="new-dispatch-scope")dispatchScopeForm();
    else if(action==="edit-dispatch-scope")dispatchScopeForm(id);
    else if(action==="edit-sender-grant")senderGrantForm(id);
    else if(action==="new-account")accountForm();
    else if(action==="edit-account")accountForm(id);
    else if(action==="audience"){state.audience=id;render();}
    else if(action==="back-report"){state.step=1;render();}
    else if(action==="back-recipients"){state.step=2;render();}
    else if(action==="review"){if(!selectedRows().length)throw new Error("請先選擇有效收件者。");state.step=3;render();window.scrollTo({top:0});}
    else if(action==="submit-send")await submitSend();
    else if(action==="clear-pending"){sessionStorage.removeItem("linePendingJob");$("modal").close();notice("已解除提交保護，請自行決定是否建立新的發送工作。");}
    else if(action==="profiles"){target.disabled=true;const result=await api('/api/profiles',{});await load();render();notice(`已更新 ${result.updated} 個 LINE 名稱，${result.failed} 個未完成。`);}
  }catch(error){if($("modal").open){$("modal-error").textContent=error.message;$("modal-error").hidden=false;}else notice(error.message,true);target.disabled=false;}
});
function updateSelection(){if($("contact-list"))$("contact-list").innerHTML=contactList();if($("selection-summary"))$("selection-summary").innerHTML=selectionSummary();if($("review-button"))$("review-button").disabled=!selectedRows().length;}
document.addEventListener("input",event=>{if(event.target.id==="contact-search"){state.search=event.target.value;state.page=1;$("contact-list").innerHTML=contactList();}});
document.addEventListener("change",event=>{const el=event.target;if(el.id==="organization-select"){localStorage.setItem(organizationKey,el.value);location.replace(location.pathname+"?view=overview");return;}if(el.id==="send-timing"){$("scheduled-time").hidden=el.value!=="scheduled";$("submit-send").textContent=el.value==="scheduled"?"確認預約":"確認立即發送";return;}if(el.dataset.select){el.checked?state.selected.add(el.dataset.select):state.selected.delete(el.dataset.select);updateSelection();}else if(["contact-kind","contact-company","contact-department"].includes(el.id)){state[{"contact-kind":"kind","contact-company":"company","contact-department":"department"}[el.id]]=el.value;state.page=1;if(el.id==="contact-company"){state.department="";render();}else $("contact-list").innerHTML=contactList();}});
document.addEventListener("submit",async event=>{event.preventDefault();const form=event.target,values=Object.fromEntries(new FormData(form)),submit=form.querySelector('[type="submit"]');if(!submit||submit.disabled)return;submit.disabled=true;$("modal-error").hidden=true;
  try{if(form.id==="contact-form")await api('/api/contact',{...values,id:form.dataset.id,...(superAdmin()?{subscribed:Boolean(form.elements.subscribed?.checked)}:{})});else if(form.id==="report-form")await api('/api/reports/save',{...values,report_id:form.dataset.id||undefined});else if(form.id==="organization-form")await api('/api/organizations/save',{...values,org_id:form.dataset.id||undefined,...Object.fromEntries(['active','reports_enabled','messaging_enabled','weather_enabled'].map(k=>[k,form.elements[k].checked]))});else if(form.id==="membership-form")await api('/api/memberships/save',{...values,active:form.elements.active.checked});else if(form.id==="dispatch-scope-form")await api('/api/dispatch-scopes/save',{...values,scope_id:form.dataset.id||undefined,active:form.elements.active.checked,recipient_ids:new FormData(form).getAll('recipient_ids')});else if(form.id==="sender-grant-form")await api('/api/sender-grants/save',{...values,scope_ids:new FormData(form).getAll('scope_ids'),report_ids:new FormData(form).getAll('report_ids'),...Object.fromEntries(['messaging','reports','weather'].map(k=>[k,form.elements[k].checked]))});else if(form.id==="account-form")await api('/api/accounts/save',{...values,active:form.elements.active.checked});else return;$("modal").close();await load();render();notice("設定已儲存。");}catch(error){$("modal-error").textContent=error.message;$("modal-error").hidden=false;submit.disabled=false;}
});
$("modal-close").addEventListener("click",()=>$("modal").close());
$("menu").addEventListener("click",()=>setSidebarOpen(!$("sidebar").classList.contains("open")));
document.addEventListener("keydown",event=>{if(event.key==="Escape"){setSidebarOpen(false);}});
$("logout").addEventListener("click",()=>{location.href="/cdn-cgi/access/logout";});
$("refresh").addEventListener("click",async()=>{if(state.busy)return;$("refresh").disabled=true;try{await load();render();notice("資料已更新。");await recoverSubmission();}catch(error){notice(error.message,true);}finally{$("refresh").disabled=false;}});
async function boot(){try{await load();render();await recoverSubmission();}catch(error){$("page").innerHTML=empty("暫時無法開啟工作台",remote?"請重新整理登入，或聯絡管理員確認帳號已啟用。":"請確認 LINE 服務已更新並啟動，再從控制台重新開啟管理頁。");notice(error.message,true);$("connection").textContent="連線未完成";}}
boot();
let polling=false;
setInterval(async()=>{if(!state.loaded||!admin()||state.busy||state.authLost||document.hidden||polling||$("modal").open)return;polling=true;try{const result=await api('/api/jobs');if(JSON.stringify(result.jobs)!==JSON.stringify(state.jobs)){state.jobs=result.jobs;if(['overview','history'].includes(state.view)){const opened=[...document.querySelectorAll('[data-job][open]')].map(el=>el.dataset.job);render();document.querySelectorAll('[data-job]').forEach(el=>{el.open=opened.includes(el.dataset.job);});}}}catch(error){notice(error.message,true);}finally{polling=false;}},6000);

// Handle unreadable image content without leaving a broken thumbnail.
document.addEventListener("error",event=>{if(event.target instanceof HTMLImageElement){const replacement=document.createElement("p");replacement.className="callout warn";replacement.textContent="圖片無法顯示，請確認來源檔案格式並重新產生報告。";event.target.replaceWith(replacement);}},true);

function scheduleLabel(value){return new Date(value).toLocaleString("zh-TW",{timeZone:"Asia/Taipei",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false});}
function scheduleFields(){return `<div class="schedule-fields"><label class="field">傳送時間<select id="send-timing"><option value="now">立即傳送</option><option value="scheduled">指定日期與時間</option></select></label><label class="field">台北時間 UTC+08:00<input type="datetime-local" id="scheduled-time" hidden></label><p class="subtitle">預約保存現在確認的文字或圖片與收件者；到期再檢查帳號、收件範圍與訂閱。電腦與 LINE 服務需開啟，延遲超過 10 分鐘標記逾期，不補發。</p></div>`;}

function organizationOptions(){return [["","選擇組織"],...(state.organizations||[]).filter(o=>o.active).map(o=>[o.org_id,o.name])];}
function organizationOverview(){return heading("組織管理","設定公司、單位、社團、俱樂部或家庭；每個組織各自授權模組與成員角色。",button("新增組織","new-organization","primary")+button("新增成員資格","new-membership"),"ORGANIZATIONS")+`<section class="panel panel-body"><h2>組織與模組</h2>${state.organizations.map(o=>`<div class="detail-row"><div><strong>${esc(o.name)}</strong><p class="subtitle">${orgKinds[o.kind]} · ${o.active?"啟用":"停用"} · ${[o.reports_enabled?"報告中心":"",o.messaging_enabled?"訊息發送":"",o.weather_enabled?"天氣模組":""].filter(Boolean).join("、")||"未授權模組"}</p></div>${button("編輯","edit-organization","small",`data-id="${esc(o.org_id)}"`)}</div>`).join("")||'<p class="callout">先建立第一個組織，再分配成員與報告。</p>'}</section><section class="panel panel-body section-space"><h2>跨組織成員資格</h2>${state.memberships.map(m=>`<div class="detail-row"><div><strong>${esc(m.email)}</strong><p class="subtitle">${esc(m.name)} · ${roleName(m.role)} · ${m.active?"啟用":"停用"}</p></div>${button("編輯","edit-membership","small",`data-id="${esc(m.email+"|"+m.org_id)}"`)}</div>`).join("")||'<p class="subtitle">尚無成員資格。</p>'}<p class="callout">同一帳號可以加入多個組織，角色與部門分開設定。平台管理員的全平台權限不受成員資格限制。</p></section>`;}
function organizationForm(id){const o=state.organizations.find(o=>o.org_id===id)||{name:"",kind:"company",active:1,reports_enabled:1,messaging_enabled:1,weather_enabled:0};modal(id?"編輯組織":"新增組織",`<form id="organization-form" data-id="${esc(id||"")}"><div class="form-grid">${field("組織名稱","name",o.name,'required maxlength="80"')}${selectField("組織類型","kind",Object.entries(orgKinds),o.kind)}${[['active','啟用組織'],['reports_enabled','授權報告中心'],['messaging_enabled','授權訊息發送與預約'],['weather_enabled','授權天氣模組']].map(([k,t])=>`<label class="check-label"><input type="checkbox" name="${k}" ${o[k]?"checked":""}>${t}</label>`).join("")}</div><p class="callout">修改名稱不改變資料歸屬。停用組織後，成員無法切換進入；未送出的組織管理員預約會重新檢查權限。</p><div class="form-actions"><button class="btn primary" type="submit">儲存組織</button></div></form>`);}
function membershipForm(id){const m=state.memberships.find(m=>m.email+"|"+m.org_id===id)||{email:"",org_id:"",role:"sender",department:"",recipient_id:"",active:1};modal("設定組織成員",`<form id="membership-form"><div class="form-grid">${selectField("登入帳號","email",state.settings.users.map(u=>[u.email,u.display_name||u.email]),m.email)}${selectField("組織","org_id",state.organizations.map(o=>[o.org_id,o.name]),m.org_id)}${selectField("此組織的角色","role",[["sender","發送人員"],["company_admin","組織管理員"],["employee","一般收件者（無後台資格）"]],m.role)}${field("部門／分組","department",m.department,'maxlength="80"')}${selectField("對應 LINE 個人聊天室","recipient_id",[["","暫不連結"],...state.contacts.filter(r=>r.kind==="user").map(r=>[r.recipient_id,label(r)+" · "+orgName(r.company)])],m.recipient_id)}<label class="check-label"><input type="checkbox" name="active" ${m.active?"checked":""}>啟用此成員資格</label></div><div class="form-actions"><button class="btn primary" type="submit">儲存成員資格</button></div></form>`);if(id){for(const k of ['email','org_id']){$("membership-form").elements[k].disabled=true;const input=document.createElement('input');input.type='hidden';input.name=k;input.value=m[k];$("membership-form").append(input);}}}

// Mobile navigation behaves as a drawer; keyboard focus stays inside until closed.
const compactNavigation=window.matchMedia('(max-width:850px)');
function setSidebarOpen(open){
  open=Boolean(open&&compactNavigation.matches);
  const wasOpen=$('sidebar').classList.contains('open');
  $('sidebar').classList.toggle('open',open);
  $('menu').setAttribute('aria-expanded',String(open));
  $('nav-backdrop').hidden=!open;
  document.body.classList.toggle('nav-open',open);
  document.querySelector('.workspace').inert=open;
  $('sidebar').inert=compactNavigation.matches&&!open;
  if(open)$('sidebar-close').focus({preventScroll:true});
  else if(wasOpen&&compactNavigation.matches)$('menu').focus({preventScroll:true});
}
$('sidebar-close').addEventListener('click',()=>setSidebarOpen(false));
$('nav-backdrop').addEventListener('click',()=>setSidebarOpen(false));
compactNavigation.addEventListener('change',()=>setSidebarOpen(false));
setSidebarOpen(false);
document.addEventListener('keydown',event=>{
  if(event.key!=='Tab'||!$('sidebar').classList.contains('open'))return;
  const controls=[...$('sidebar').querySelectorAll('a[href],button:not(:disabled)')].filter(el=>el.getClientRects().length&&!el.hidden);
  const first=controls[0],last=controls.at(-1);
  if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}
  else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
});

function organizationsPage(){return organizationOverview()+`<section class="panel section-space"><div class="panel-head"><div><h2>發送範圍</h2><p>部門依分類更新；專案指定多個對象；群組指定一個聊天室。</p></div>${button("新增範圍","new-dispatch-scope","primary")}</div><div class="panel-body">${(state.settings.dispatch_scopes||[]).map(s=>`<div class="detail-row"><div><strong>${esc(s.name)}</strong><p class="subtitle">${esc(orgName(s.company))} · ${{department:"部門",project:"專案",group:"群組"}[s.kind]} · ${s.active?"啟用":"停用"}${s.department?" · "+esc(s.department):" · "+s.recipient_ids.length+" 個對象"}</p></div>${button("編輯","edit-dispatch-scope","small",`data-id="${esc(s.scope_id)}"`)}</div>`).join("")||'<p class="callout">先建立收件範圍，再授權給發送人員。</p>'}</div></section><section class="panel section-space"><div class="panel-head"><h2>發送人員授權</h2></div><div class="panel-body">${state.memberships.filter(m=>m.role==="sender").map(m=>{const g=(state.settings.sender_grants||[]).find(g=>g.email===m.email&&g.company===m.org_id);return `<div class="detail-row"><div><strong>${esc(m.email)}</strong><p class="subtitle">${esc(m.name)} · ${g?.scope_ids.length||0} 個範圍 · ${g?.report_ids.length||0} 份報告 · ${g?.messaging?"已授權發送":"未授權發送"}</p></div>${button("設定授權","edit-sender-grant","small",`data-id="${esc(m.email+"|"+m.org_id)}"`)}</div>`;}).join("")||'<p class="callout">到「帳號與設定」新增發送人員，或將既有登入帳號加入組織並選擇發送人員角色。一般 LINE 收件者不需要後台帳號。</p>'}</div></section>`;}
function checkChoices(name,items,selected=[]){return `<div class="permission-choices">${items.map(([id,text])=>`<label class="check-label"><input type="checkbox" name="${name}" value="${esc(id)}" ${selected.includes(id)?"checked":""}>${esc(text)}</label>`).join("")||'<p class="muted">目前沒有可選項目。</p>'}</div>`;}
function dispatchScopeForm(id){const s=(state.settings.dispatch_scopes||[]).find(s=>s.scope_id===id)||{company:state.organizations[0]?.org_id||"",name:"",kind:"department",department:"",recipient_ids:[],active:1};modal(id?"編輯發送範圍":"新增發送範圍",`<form id="dispatch-scope-form" data-id="${esc(id||"")}"><div class="form-grid">${selectField("所屬組織","company",organizationOptions(),s.company)}${field("範圍名稱","name",s.name,'required maxlength="80" placeholder="例如：北區業務、網站改版專案"')}${selectField("範圍類型","kind",[["department","部門"],["project","專案"],["group","LINE 群組"]],s.kind)}${field("部門名稱（部門範圍必填）","department",s.department,'maxlength="60"')}<label class="check-label full"><input name="active" type="checkbox" ${s.active?"checked":""}>啟用範圍</label></div><fieldset class="permission-fieldset"><legend>範圍內收件者</legend><div id="scope-recipient-options"></div></fieldset><p class="callout">部門會包含同組織、同部門分類的聊天室。專案可選多個對象；LINE 群組只能選一個。停用範圍會影響尚未執行的預約。</p><div class="form-actions"><button class="btn primary" type="submit">儲存範圍</button></div></form>`);const form=$("dispatch-scope-form");if(id){form.elements.company.disabled=true;form.insertAdjacentHTML('beforeend',`<input type="hidden" name="company" value="${esc(s.company)}">`);}function choices(selected=[]){const company=id?s.company:form.elements.company.value,kind=form.elements.kind.value;$("scope-recipient-options").innerHTML=kind==="department"?'<p class="muted">依上方部門名稱自動比對，不需逐筆選人。</p>':checkChoices('recipient_ids',state.contacts.filter(r=>r.company===company&&(kind!=="group"||r.kind!=="user")).map(r=>[r.recipient_id,label(r)+(r.active?"":"（已停用）")]),selected);}choices(s.recipient_ids);form.addEventListener('change',e=>{if(['company','kind'].includes(e.target.name))choices();});}
function senderGrantForm(id){const m=state.memberships.find(m=>m.email+"|"+m.org_id===id);if(!m)return;const g=(state.settings.sender_grants||[]).find(g=>g.email===m.email&&g.company===m.org_id)||{scope_ids:[],report_ids:[]};modal("設定發送授權",`<form id="sender-grant-form"><input type="hidden" name="email" value="${esc(m.email)}"><input type="hidden" name="company" value="${esc(m.org_id)}"><p>${esc(m.email)} · ${esc(m.name)}</p><fieldset class="permission-fieldset"><legend>可用模組</legend>${[['messaging','訊息發送與預約'],['reports','報告中心'],['weather','個人天氣模組（組織也須啟用）']].map(([key,text])=>`<label class="check-label"><input type="checkbox" name="${key}" ${g[key]?"checked":""}>${text}</label>`).join('')}</fieldset><fieldset class="permission-fieldset"><legend>可發送對象範圍（可複選）</legend>${checkChoices('scope_ids',(state.settings.dispatch_scopes||[]).filter(s=>s.company===m.org_id).map(s=>[s.scope_id,s.name+(s.active?'':'（已停用）')]),g.scope_ids)}</fieldset><fieldset class="permission-fieldset"><legend>可查看與發送的報告（可複選）</legend>${checkChoices('report_ids',(state.settings.report_sources||[]).filter(r=>r.company===m.org_id||r.report_id==='weather').map(r=>[r.report_id,r.title]),g.report_ids)}</fieldset><p class="callout">報告與收件範圍分別授權。勾選報告不會開放全部收件者；同時仍須符合報告本身的部門／個人限制。只發文字或自訂圖片時，可不選報告。取消模組或範圍會在預約執行前重新檢查。</p><div class="form-actions"><button class="btn primary" type="submit">儲存授權</button></div></form>`);}
