"""所有數量上限的唯一定義處（單台 PC 規模）。

各模組一律 `import limits` 引用，不得在程式中另寫數字；前端顯示「目前數量／上限」
時由 API 回傳這裡的值。規格出處標在每一項後方。
"""

# 聯絡對象與標籤（聯絡人管理規格 12.3）
TAGS_PER_OA = 100
TAGS_PER_CONTACT = 30
BULK_CONTACTS = 200
SAVED_FILTERS_PER_OA = 10              # 聯絡人管理規格 13.2

# 對話記事本（對話記事本管理規格 9 與 10）
NOTES_PER_ROOM = 100
PINNED_NOTES_PER_ROOM = 5
NOTE_TAGS_PER_OA = 30
TAGS_PER_NOTE = 5
NOTE_CONTENT_MAX = 2000
NOTE_TRASH_DAYS = 30
NOTE_CATEGORIES_PER_OA = 50

# 聊天（聊天規格 12.3、12.5、14）
CANNED_REPLIES_PER_OA = 100
SCHEDULED_MESSAGES_PER_OA = 50
TEXT_MESSAGE_MAX = 5000                # LINE 文字訊息上限
MESSAGES_PAGE_SIZE = 50
ROOMS_PAGE_SIZE = 50
RESPONSE_HOLIDAYS_MAX = 100
SINGLE_MEDIA_MAX_BYTES = 20 * 1024 * 1024          # 20 MB
TOTAL_MEDIA_MAX_BYTES = 10 * 1024 * 1024 * 1024    # 10 GB
MEDIA_RETENTION_DAYS = 365

# 案件、範本包與分類（案件管理流程規格 16、17）
CASE_EXPORT_MAX = 5000
CATEGORIES_PER_OA = 20                 # 記事類型與案件類別各自上限
CUSTOM_PACKS_PER_WORKSPACE = 20
TEMPLATES_PER_PACK = 20                # 案件範本與記事範本各自上限


# 值日生（單台 PC 首期容量與輸入保護）
DUTY_PEOPLE_PER_ORG = 200
DUTY_TASKS_PER_ORG = 200
DUTY_ITEMS_PER_TASK = 30
DUTY_BULK_PEOPLE = 100
DUTY_NAME_MAX = 80
DUTY_CONTENT_MAX = 2000
DUTY_EXCLUDED_DATES_MAX = 100
DUTY_PREVIEW_DAYS = 14
DUTY_ROSTERS_PER_ORG = 500
DUTY_SUBSTITUTIONS_PER_ASSIGNMENT = 30
DUTY_CSV_MAX_BYTES = 2 * 1024 * 1024
DUTY_CSV_ROWS_MAX = DUTY_TASKS_PER_ORG * DUTY_ITEMS_PER_TASK
DUTY_NOTICE_JOBS_PER_ORG = 10000
DUTY_NOTICE_PAGE_SIZE = 100
DUTY_NOTICE_HORIZON_DAYS = 31
DUTY_NOTICE_CATCHUP_MAX_MINUTES = 1440
DUTY_ROTATION_PREVIEW_PERIODS = 3
DUTY_ROTATION_STEP_MAX = 200

# 表單與回覆管理（2026-10-07 使用者確認）
FORMS_PER_OA = 100
FORM_QUESTIONS_MAX = 100
FORM_OPTIONS_MAX = 100
FORM_NAME_MAX = 80
FORM_TEXT_MAX = 5000
FORM_ATTACHMENT_MAX_BYTES = 20 * 1024 * 1024
FORM_ATTACHMENTS_PER_QUESTION = 5
FORM_ATTACHMENT_TOTAL_MAX_BYTES = 50 * 1024 * 1024
FORM_TEMP_RETENTION_HOURS = 24
# 包含題目／選項設定的請求容量，依已確認的數量與文字上限推導。
FORM_DESIGN_MAX_BYTES = FORM_QUESTIONS_MAX * (FORM_OPTIONS_MAX + 4) * (FORM_TEXT_MAX * 4 + FORM_NAME_MAX + 256)

def as_dict() -> dict:
    """供前端顯示「目前數量／上限」使用。"""
    return {k: v for k, v in globals().items() if k.isupper() and isinstance(v, int)}
